[package]
name = "lkjscript-native-cache"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
lkjscript-contracts = { path = "../lkjscript-contracts" }
lkjscript-core = { path = "../lkjscript-core" }
lkjscript-native = { path = "../lkjscript-native" }

[lints]
workspace = true
