#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum BudgetAuthority {
    CompileRequest,
    SemanticRequest,
    Transaction,
    Proof,
    ArtifactBuild,
    Execution,
    SourceLoading,
    Parsing,
    SchemaValidation,
    Diagnostics,
    Resolution,
    TypeAnalysis,
    TraitAnalysis,
    OwnershipAnalysis,
    Hir,
    Effects,
    PatternUsefulness,
    PatternLowering,
    SsaConstruction,
    SsaVerification,
    Normalization,
    ProofDiscovery,
    ProofChecking,
    Bytecode,
    NativeLowering,
    ProtocolDecode,
    ProtocolEncode,
    Holes,
    SessionCaching,
    RepositoryQueries,
}

impl BudgetAuthority {
    pub const ALL: [Self; 30] = [
        Self::CompileRequest,
        Self::SemanticRequest,
        Self::Transaction,
        Self::Proof,
        Self::ArtifactBuild,
        Self::Execution,
        Self::SourceLoading,
        Self::Parsing,
        Self::SchemaValidation,
        Self::Diagnostics,
        Self::Resolution,
        Self::TypeAnalysis,
        Self::TraitAnalysis,
        Self::OwnershipAnalysis,
        Self::Hir,
        Self::Effects,
        Self::PatternUsefulness,
        Self::PatternLowering,
        Self::SsaConstruction,
        Self::SsaVerification,
        Self::Normalization,
        Self::ProofDiscovery,
        Self::ProofChecking,
        Self::Bytecode,
        Self::NativeLowering,
        Self::ProtocolDecode,
        Self::ProtocolEncode,
        Self::Holes,
        Self::SessionCaching,
        Self::RepositoryQueries,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::CompileRequest => "compile_request",
            Self::SemanticRequest => "semantic_request",
            Self::Transaction => "transaction",
            Self::Proof => "proof",
            Self::ArtifactBuild => "artifact_build",
            Self::Execution => "execution",
            Self::SourceLoading => "source_loading",
            Self::Parsing => "parsing",
            Self::SchemaValidation => "schema_validation",
            Self::Diagnostics => "diagnostics",
            Self::Resolution => "resolution",
            Self::TypeAnalysis => "type_analysis",
            Self::TraitAnalysis => "trait_analysis",
            Self::OwnershipAnalysis => "ownership_analysis",
            Self::Hir => "hir",
            Self::Effects => "effects",
            Self::PatternUsefulness => "pattern_usefulness",
            Self::PatternLowering => "pattern_lowering",
            Self::SsaConstruction => "ssa_construction",
            Self::SsaVerification => "ssa_verification",
            Self::Normalization => "normalization",
            Self::ProofDiscovery => "proof_discovery",
            Self::ProofChecking => "proof_checking",
            Self::Bytecode => "bytecode",
            Self::NativeLowering => "native_lowering",
            Self::ProtocolDecode => "protocol_decode",
            Self::ProtocolEncode => "protocol_encode",
            Self::Holes => "holes",
            Self::SessionCaching => "session_caching",
            Self::RepositoryQueries => "repository_queries",
        }
    }
}
