use super::ResourceCategory;

impl ResourceCategory {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::SourceBytes => "source_bytes",
            Self::SourceUnits => "source_units",
            Self::ImportEdges => "import_edges",
            Self::Tokens => "tokens",
            Self::SchemaNodes => "schema_nodes",
            Self::TopLevelDeclarations => "top_level_declarations",
            Self::ProductFields => "product_fields",
            Self::ParserWork => "parser_work",
            Self::ValidationWork => "validation_work",
            Self::PathWork => "path_work",
            Self::TypeNesting => "type_nesting",
            Self::TypeWork => "type_work",
            Self::TraitWork => "trait_work",
            Self::OwnershipExpressions => "ownership_expressions",
            Self::OwnershipRetainedState => "ownership_retained_state",
            Self::HirFunctions => "hir_functions",
            Self::HirExpressions => "hir_expressions",
            Self::SsaFunctions => "ssa_functions",
            Self::SsaBlocks => "ssa_blocks",
            Self::SsaValues => "ssa_values",
            Self::SsaEdges => "ssa_edges",
            Self::SsaFrameStates => "ssa_frame_states",
            Self::Diagnostics => "diagnostics",
            Self::ProtocolRequestBytes => "protocol_request_bytes",
            Self::ProtocolResponseBytes => "protocol_response_bytes",
            Self::EnumDeclarations => "enum_declarations",
            Self::EnumVariants => "enum_variants",
            Self::VariantFields => "variant_fields",
            Self::EnumRecursionWork => "enum_recursion_work",
            Self::Patterns => "patterns",
            Self::MatchArms => "match-arms",
            Self::UsefulnessRows => "usefulness_rows",
            Self::UsefulnessColumns => "usefulness_columns",
            Self::UsefulnessSpecializationWork => "usefulness_specialization_work",
            Self::MatchPlans => "match_plans",
            Self::ExhaustivenessWitnessBytes => "exhaustiveness_witness_bytes",
            Self::HoleCount => "hole_count",
            Self::HoleCandidates => "hole_candidates",
            Self::HoleSearchWork => "hole_search_work",
            Self::LegalActions => "legal-actions",
            Self::SemanticSessionLifetimeFuel => "semantic_session_lifetime_fuel",
            Self::SemanticSessionInputBytes => "semantic_session_input_bytes",
            Self::SemanticSessionOutputBytes => "semantic_session_output_bytes",
            Self::SemanticSessionNodes => "semantic_session_nodes",
            Self::SemanticSessionSnapshots => "semantic_session_snapshots",
            Self::SemanticSessionRetainedBytes => "semantic_session_retained_bytes",
            Self::SemanticSessionCacheEntries => "semantic_session_cache_entries",
            Self::SemanticSessionCachedRevisions => "semantic_session_cached_revisions",
            Self::Transactions => "transactions",
            Self::TransactionOperations => "transaction_operations",
            Self::TransactionImpactNodes => "transaction_impact_nodes",
            Self::StagedPublicationBytes => "staged_publication_bytes",
            Self::StagedPublicationNodes => "staged_publication_nodes",
            Self::LogicalAggregateConstructions => "logical_aggregate_constructions",
        }
    }
}
