use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(110),
        arity: 1,
        type_scheme: "forall t e fn inputs result t e output t",
        generic_variables: &["t", "e"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(111),
        arity: 1,
        type_scheme: "forall t e fn inputs result t e output e",
        generic_variables: &["t", "e"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(112),
        arity: 1,
        type_scheme: "forall t fn inputs t output option t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(113),
        arity: 1,
        type_scheme: "forall t fn inputs option t output bool",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(114),
        arity: 1,
        type_scheme: "forall t fn inputs option t output t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(115),
        arity: 1,
        type_scheme: "fn inputs bytes output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(116),
        arity: 2,
        type_scheme: "fn inputs bytes i64 output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(117),
        arity: 3,
        type_scheme: "fn inputs bytes i64 i64 output bytes",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(35),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(118),
        arity: 1,
        type_scheme: "fn inputs bytes output bytes",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(35),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(119),
        arity: 1,
        type_scheme: "fn inputs byte-vector output bytes",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(38),
        capability_requirements: &[],
        ownership: OperationOwnership::ConsumesOwner,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
