use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(50),
        arity: 1,
        type_scheme: "fn inputs i64 output string",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(51),
        arity: 1,
        type_scheme: "fn inputs f64 output string",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(52),
        arity: 1,
        type_scheme: "fn inputs capability stdio output input-stream",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(53),
        arity: 1,
        type_scheme: "fn inputs input-stream output result bool system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(54),
        arity: 1,
        type_scheme: "forall resource fn inputs resource output result unit system-error",
        generic_variables: &["resource"],
        generic_constraints: &[concat!(
            "resource:one-of(output-stream,file-reader,file-writer,file-appender,",
            "directory,tcp-listener,tcp-stream,sqlite-connection,",
            "sqlite-statement,terminal-session)",
        )],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::ConsumesResource,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(55),
        arity: 1,
        type_scheme: "forall resource fn inputs resource output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(input-stream,file-reader,tcp-stream)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(56),
        arity: 2,
        type_scheme: "forall resource fn inputs resource i64 output result unit system-error",
        generic_variables: &["resource"],
        generic_constraints: &[
            "resource:one-of(output-stream,file-writer,file-appender,tcp-stream)",
        ],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(57),
        arity: 2,
        type_scheme:
            "forall resource fn inputs resource byte-slice-mut output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(input-stream,file-reader,tcp-stream)"],
        effects: OperationEffects(53),
        capability_requirements: &[],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(58),
        arity: 2,
        type_scheme: "forall resource fn inputs resource byte-slice output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &[
            "resource:one-of(output-stream,file-writer,file-appender,tcp-stream)",
        ],
        effects: OperationEffects(51),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(59),
        arity: 2,
        type_scheme: "fn inputs capability terminal byte-slice output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Terminal],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
