use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(10),
        arity: 1,
        type_scheme: "fn inputs f64 output result i64 numeric-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::NumericConversion,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(11),
        arity: 1,
        type_scheme: "fn inputs f64 output result i64 numeric-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::NumericConversion,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(12),
        arity: 2,
        type_scheme: "forall n fn inputs n n output bool",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(13),
        arity: 2,
        type_scheme: "forall n fn inputs n n output bool",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(14),
        arity: 2,
        type_scheme: "forall n fn inputs n n output bool",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(15),
        arity: 2,
        type_scheme: "forall n fn inputs n n output bool",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(16),
        arity: 1,
        type_scheme: "fn inputs bool output bool",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(17),
        arity: 2,
        type_scheme: "forall t fn inputs t list t output list t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(18),
        arity: 1,
        type_scheme: "forall t fn inputs list t output t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(19),
        arity: 1,
        type_scheme: "forall t fn inputs list t output list t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
