use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(0),
        arity: 2,
        type_scheme: "forall n fn inputs n n output n",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(32),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(1),
        arity: 2,
        type_scheme: "forall n fn inputs n n output n",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(32),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(2),
        arity: 2,
        type_scheme: "forall n fn inputs n n output n",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(32),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(3),
        arity: 2,
        type_scheme: "forall n fn inputs n n output n",
        generic_variables: &["n"],
        generic_constraints: &[],
        effects: OperationEffects(32),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(4),
        arity: 2,
        type_scheme: "forall t fn inputs t t output bool",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(5),
        arity: 2,
        type_scheme: "forall t fn inputs t t output bool",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(6),
        arity: 2,
        type_scheme: "forall t fn inputs list t list t output bool",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(7),
        arity: 2,
        type_scheme: "fn inputs f64 f64 output bool",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(8),
        arity: 1,
        type_scheme: "fn inputs i64 output result f64 numeric-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::NumericConversion,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(9),
        arity: 1,
        type_scheme: "fn inputs i64 output f64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::NumericConversion,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
