use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(60),
        arity: 1,
        type_scheme: "fn inputs capability terminal output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Terminal],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(61),
        arity: 2,
        type_scheme: "fn inputs capability file-system path output result file-reader system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(62),
        arity: 2,
        type_scheme: "fn inputs capability file-system path output result file-writer system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(63),
        arity: 2,
        type_scheme:
            "fn inputs capability file-system path output result file-appender system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(64),
        arity: 2,
        type_scheme: "fn inputs capability file-system path output result file-writer system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(65),
        arity: 2,
        type_scheme: "fn inputs capability file-system path output result directory system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(66),
        arity: 1,
        type_scheme: "forall resource fn inputs resource output result unit system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(file-writer,file-appender,directory)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(67),
        arity: 2,
        type_scheme: "forall resource fn inputs resource i64 output result unit system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(file-writer,file-appender)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(68),
        arity: 3,
        type_scheme: "fn inputs capability file-system path path output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(69),
        arity: 2,
        type_scheme: "fn inputs capability entropy byte-slice-mut output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Entropy],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
