use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(100),
        arity: 2,
        type_scheme: "fn inputs tcp-listener i64 output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(101),
        arity: 1,
        type_scheme: "fn inputs tcp-listener output result tcp-stream system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(102),
        arity: 1,
        type_scheme: "fn inputs tcp-stream output result string system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(103),
        arity: 2,
        type_scheme: "fn inputs tcp-stream string output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(104),
        arity: 2,
        type_scheme: "forall resource fn inputs resource i64 output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(input-stream,file-reader,tcp-listener,tcp-stream)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(105),
        arity: 2,
        type_scheme: "fn inputs input-stream byte-slice-mut output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(106),
        arity: 2,
        type_scheme: "fn inputs input-stream byte-slice output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(107),
        arity: 1,
        type_scheme: "forall t e fn inputs t output result t e",
        generic_variables: &["t", "e"],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(108),
        arity: 1,
        type_scheme: "forall t e fn inputs e output result t e",
        generic_variables: &["t", "e"],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(109),
        arity: 1,
        type_scheme: "forall t e fn inputs result t e output bool",
        generic_variables: &["t", "e"],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
