use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(90),
        arity: 3,
        type_scheme: "fn inputs sqlite-statement i64 string output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(91),
        arity: 3,
        type_scheme: "fn inputs sqlite-statement i64 buf output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(92),
        arity: 1,
        type_scheme: "fn inputs sqlite-statement output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(93),
        arity: 1,
        type_scheme: "fn inputs sqlite-statement output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(94),
        arity: 2,
        type_scheme: "fn inputs sqlite-statement i64 output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(95),
        arity: 2,
        type_scheme: "fn inputs sqlite-statement i64 output result option i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(96),
        arity: 2,
        type_scheme: "fn inputs sqlite-statement i64 output result option f64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(97),
        arity: 2,
        type_scheme: "fn inputs sqlite-statement i64 output result option string system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(98),
        arity: 2,
        type_scheme: "fn inputs sqlite-statement i64 output result option buf system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(99),
        arity: 1,
        type_scheme: "fn inputs sqlite-connection output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
