use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(90),
        arity: 2,
        type_scheme: "fn inputs sqlite-statement i64 output result option bytes system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(91),
        arity: 1,
        type_scheme: "fn inputs sqlite-connection output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(92),
        arity: 1,
        type_scheme: "fn inputs sqlite-connection output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(93),
        arity: 1,
        type_scheme: "fn inputs sqlite-connection output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(94),
        arity: 4,
        type_scheme:
            "fn inputs capability sqlite sqlite-connection path i64 output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Sqlite],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(95),
        arity: 2,
        type_scheme: "fn inputs capability file-system path output result bool system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(96),
        arity: 2,
        type_scheme: "fn inputs capability clock i64 output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Clock],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(97),
        arity: 1,
        type_scheme: "fn inputs capability clock output result i64 system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Clock],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(98),
        arity: 1,
        type_scheme: "fn inputs capability network output result tcp-listener system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Network],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(99),
        arity: 2,
        type_scheme: "fn inputs tcp-listener i64 output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
