use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(120),
        arity: 1,
        type_scheme: "forall t fn inputs t output option t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(121),
        arity: 1,
        type_scheme: "forall t fn inputs option t output bool",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(122),
        arity: 1,
        type_scheme: "forall t fn inputs option t output t",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Enum,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
