use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(60),
        arity: 1,
        type_scheme: "fn inputs capability stdio output input-stream",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(61),
        arity: 1,
        type_scheme: "fn inputs input-stream output result bool system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(62),
        arity: 1,
        type_scheme: "forall resource fn inputs resource output result unit system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(output-stream,file-reader,file-writer,file-appender,directory,tcp-listener,tcp-stream,sqlite-connection,sqlite-statement,terminal-session)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::ConsumesResource,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(63),
        arity: 1,
        type_scheme: "forall resource fn inputs resource output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(input-stream,file-reader,tcp-stream)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(64),
        arity: 2,
        type_scheme: "forall resource fn inputs resource i64 output result unit system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(output-stream,file-writer,file-appender,tcp-stream)"],
        effects: OperationEffects(49),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(65),
        arity: 4,
        type_scheme:
            "forall resource fn inputs resource buf i64 i64 output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(input-stream,file-reader,tcp-stream)"],
        effects: OperationEffects(53),
        capability_requirements: &[],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(66),
        arity: 4,
        type_scheme:
            "forall resource fn inputs resource buf i64 i64 output result i64 system-error",
        generic_variables: &["resource"],
        generic_constraints: &["resource:one-of(output-stream,file-writer,file-appender,tcp-stream)"],
        effects: OperationEffects(51),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(67),
        arity: 2,
        type_scheme: "fn inputs capability terminal buf output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Terminal],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(68),
        arity: 1,
        type_scheme: "fn inputs capability terminal output result unit system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Terminal],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(69),
        arity: 2,
        type_scheme: "fn inputs capability file-system path output result file-reader system-error",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::FileSystem],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
