use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(20),
        arity: 1,
        type_scheme: "forall t fn inputs list t output bool",
        generic_variables: &["t"],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(21),
        arity: 2,
        type_scheme: "fn inputs capability stdio string output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(22),
        arity: 1,
        type_scheme: "fn inputs capability stdio output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(23),
        arity: 1,
        type_scheme: "fn inputs capability stdio output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(24),
        arity: 2,
        type_scheme: "fn inputs capability stdio i64 output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(25),
        arity: 1,
        type_scheme: "fn inputs i64 output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(112),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Control,
        semantic_source: SemanticSourceRelationship::ControlForm,
        legal_action_available: false,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(26),
        arity: 2,
        type_scheme: "fn inputs i64 i64 output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(27),
        arity: 2,
        type_scheme: "fn inputs i64 i64 output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(28),
        arity: 2,
        type_scheme: "fn inputs i64 i64 output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(29),
        arity: 2,
        type_scheme: "fn inputs bool bool output bool",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Control,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
