use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(30),
        arity: 2,
        type_scheme: "fn inputs bool bool output bool",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(0),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::Control,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(31),
        arity: 2,
        type_scheme: "fn inputs capability stdio string output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Stdio],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(32),
        arity: 0,
        type_scheme: "fn inputs  output string",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(33),
        arity: 1,
        type_scheme: "fn inputs capability arguments output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Arguments],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(34),
        arity: 2,
        type_scheme: "fn inputs capability arguments i64 output option string",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(49),
        capability_requirements: &[CapabilityKind::Arguments],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(35),
        arity: 1,
        type_scheme: "fn inputs i64 output byte-vector",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(33),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(36),
        arity: 1,
        type_scheme: "fn inputs byte-slice output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(2),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: false,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(37),
        arity: 2,
        type_scheme: "fn inputs byte-slice i64 output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(38),
        arity: 3,
        type_scheme: "fn inputs byte-slice-mut i64 i64 output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(36),
        capability_requirements: &[],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(39),
        arity: 1,
        type_scheme: "fn inputs string output bytes",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(35),
        capability_requirements: &[],
        ownership: OperationOwnership::Allocates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
