use super::*;

pub(super) const RECORDS: &[OperationSemanticsRecord] = &[
    OperationSemanticsRecord {
        identity: OperationIdentity::new(120),
        arity: 1,
        type_scheme: "fn inputs bytes output byte-vector",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(39),
        capability_requirements: &[],
        ownership: OperationOwnership::ConsumesOwner,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(121),
        arity: 2,
        type_scheme: "fn inputs byte-slice i64 output i64",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(34),
        capability_requirements: &[],
        ownership: OperationOwnership::Observes,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
    OperationSemanticsRecord {
        identity: OperationIdentity::new(122),
        arity: 3,
        type_scheme: "fn inputs byte-slice-mut i64 i64 output unit",
        generic_variables: &[],
        generic_constraints: &[],
        effects: OperationEffects(36),
        capability_requirements: &[],
        ownership: OperationOwnership::Mutates,
        may_trap: true,
        may_diverge: false,
        runtime_lowering: RuntimeLowering::RuntimeCall,
        semantic_source: SemanticSourceRelationship::BuiltinCall,
        legal_action_available: true,
    },
];
