[workspace]
members = [
    "crates/lkjscript-contracts",
    "crates/lkjscript-ir",
    "crates/lkjscript-core",
    "crates/lkjscript-resource",
    "crates/lkjscript-host",
    "crates/lkjscript-database",
    "crates/lkjscript-compiler",
    "crates/lkjscript-native",
    "crates/lkjscript-jit",
    "crates/lkjscript-sys",
    "crates/lkjscript-vm",
    "crates/lkjscript-runtime",
    "crates/lkjscript-app",
    "crates/lkjscript-xtask",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.0.0"
publish = false

[workspace.dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"

[workspace.lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"
