use super::*;

fn input() -> Value {
    json!([
        {"product":"demo", "version":"1", "capabilities":"abc"},
        [{"code":"a|`<&", "class":"source", "meaning":"日本語🌱 <x> &", "retry":"a\nb"}],
        [{"status":-7, "meaning":"do not retry"}]
    ])
}

#[test]
fn native_layout_escapes_fields_without_markdown_delimiter_ambiguity() {
    let actual = render("diagnostics", input()).expect("native rendering");
    let expected = concat!(
        "<!-- Generated by `lkjscript capabilities --generate-docs docs/generated`. ",
        "Do not edit. demo 1 capabilities `abc`. -->\n\n",
        "# Protocol diagnostics and exit statuses\n\n",
        "<table>\n<thead>\n<tr><th>Code</th><th>Class</th><th>Stable meaning</th><th>Retry guidance</th></tr>\n",
        "</thead>\n<tbody>\n<tr><td><code>a|`&lt;&amp;</code></td><td><code>source</code></td>",
        "<td>日本語🌱 &lt;x&gt; &amp;</td><td>a\nb</td></tr>\n</tbody>\n</table>\n\n",
        "<table>\n<thead>\n<tr><th>Exit</th><th>Meaning</th></tr>\n</thead>\n<tbody>\n",
        "<tr><td>-7</td><td>do not retry</td></tr>\n</tbody>\n</table>\n",
    );
    assert_eq!(actual, expected);
}

#[test]
fn native_input_requires_exact_typed_records_and_target() {
    let mut missing = input();
    missing[0]
        .as_object_mut()
        .expect("build record")
        .remove("version");
    assert!(render("diagnostics", missing).is_err());
    let mut unknown = input();
    unknown[0]["extra"] = json!(true);
    assert!(render("diagnostics", unknown).is_err());
    let mut wrong_type = input();
    wrong_type[2][0]["status"] = json!("7");
    assert!(render("diagnostics", wrong_type).is_err());
    assert!(render("absent", input()).is_err());
}

#[test]
fn native_rendering_preserves_input_order_and_dynamic_header() {
    let mut values = input();
    values[0]["product"] = json!("custom <product>");
    values[1].as_array_mut().expect("diagnostics").push(json!({
        "code":"second", "class":"resource", "meaning":"next", "retry":"never"
    }));
    let result = render("diagnostics", values).expect("ordered rendering");
    assert!(result.contains("custom &lt;product&gt; 1 capabilities `abc`"));
    assert!(result.find("a|`").expect("first") < result.find("second").expect("second"));
}

#[test]
fn immutable_native_artifact_still_uses_cancellation_and_output_admission() {
    let input = serde_json::to_vec(&input()).expect("JSON input");
    let control = ExecutionControl::uncancelled();
    control.cancel();
    let target = Name::new("diagnostics").expect("target");
    let error = run_pure_artifact_command(
        program().expect("program"),
        &target,
        &input,
        NormalizedCommandPolicy::default(),
        &control,
    )
    .expect_err("cancelled native rendering");
    assert_eq!(
        error.class,
        crate::platform::diagnostic::DiagnosticClass::Cancelled
    );
    let mut policy = NormalizedCommandPolicy::default();
    policy.json.maximum_bytes = 512;
    let error = run_pure_artifact_command(
        program().expect("program"),
        &target,
        &input,
        policy,
        &ExecutionControl::uncancelled(),
    )
    .expect_err("rendered output exceeds input-fitting bound");
    assert_eq!(error.code, "normalized_json_output_bytes");
}

#[test]
fn native_operations_keep_typed_columns_and_escape_runner_observations() {
    let result = render("operations", json!([
        {"product":"demo", "version":"1", "capabilities":"abc"},
        [{"name":"sample", "request":"in", "response":"out", "authority":"none", "usage":"a|`<b>"}],
        [
            {"name":"first", "purpose":"A&B", "runner":"command", "deployment":false, "artifact":"none"},
            {"name":"second", "purpose":"live", "runner":"http", "deployment":true, "artifact":"app.lkja"}
        ],
        "```<svg>&\n"
    ])).expect("native operation guide");
    assert!(result.contains(concat!(
        "<tr><td><code>sample</code></td><td><code>in</code></td>",
        "<td><code>out</code></td><td><code>none</code></td>",
        "<td><code>a|`&lt;b&gt;</code></td></tr>\n"
    )));
    assert!(result.contains(concat!(
        "<tr><td><code>first</code></td><td>A&amp;B</td><td><code>command</code></td>",
        "<td><code>false</code></td><td><code>none</code></td></tr>\n"
    )));
    assert!(result.contains("<td><code>true</code></td><td><code>app.lkja</code></td>"));
    assert!(result.ends_with("<pre>```&lt;svg&gt;&amp;\n</pre>\n"));
}
