services:
  lkjscript2026:
    profiles: ["run"]
    build:
      context: ..
      dockerfile: meta/Dockerfile
      target: runtime
    command: ["run", "src/examples/hello/main.lkjml"]
    working_dir: /usr/local/share/lkjscript2026
    stdin_open: true
    tty: true

  mandelbrot:
    profiles: ["run"]
    build:
      context: ..
      dockerfile: meta/Dockerfile
      target: runtime
    command: ["run", "src/examples/mandel/main.lkjml"]
    working_dir: /usr/local/share/lkjscript2026
    stdin_open: true
    tty: true

  texteditor:
    profiles: ["run"]
    build:
      context: ..
      dockerfile: meta/Dockerfile
      target: runtime
    command: ["run", "src/examples/texteditor/main.lkjml"]
    working_dir: /usr/local/share/lkjscript2026
    stdin_open: true
    tty: true

  http:
    profiles: ["run"]
    build:
      context: ..
      dockerfile: meta/Dockerfile
      target: runtime
    command: ["run", "src/examples/http/hello.lkjml"]
    working_dir: /usr/local/share/lkjscript2026
    ports:
      - "8080:8080"

  verify:
    profiles: ["verify"]
    build:
      context: ..
      dockerfile: meta/Dockerfile
      target: verified
    entrypoint: ["cat"]
    command: ["/tmp/lkjscript2026-verification-result"]
