use super::{record, OperationCategory as C, OperationVocabularyRecord as R};

pub(super) const RECORDS: &[R] = &[
    record(0, "add", "add", C::Arithmetic, "checked numeric addition"),
    record(
        1,
        "subtract",
        "subtract",
        C::Arithmetic,
        "checked numeric subtraction",
    ),
    record(
        2,
        "multiply",
        "multiply",
        C::Arithmetic,
        "checked numeric multiplication",
    ),
    record(
        3,
        "divide",
        "divide",
        C::Arithmetic,
        "checked numeric division",
    ),
    record(
        4,
        "equal-value",
        "equal-value",
        C::Equality,
        "typed value equality",
    ),
    record(
        5,
        "same-object",
        "is-same-object",
        C::Equality,
        "object identity predicate",
    ),
    record(
        6,
        "list-equal",
        "equal-list",
        C::Equality,
        "typed list equality",
    ),
    record(
        7,
        "f64-bits-equal",
        "equal-f64-bits",
        C::Equality,
        "f64 bit equality",
    ),
    record(
        8,
        "f64-from-i64-exact",
        "convert-i64-to-f64-exact",
        C::Conversion,
        "exact conversion",
    ),
    record(
        9,
        "f64-from-i64-rounded",
        "convert-i64-to-f64-rounded",
        C::Conversion,
        "rounded conversion",
    ),
    record(
        10,
        "i64-from-f64-exact",
        "convert-f64-to-i64-exact",
        C::Conversion,
        "exact conversion",
    ),
    record(
        11,
        "i64-from-f64-trunc",
        "convert-f64-to-i64-truncating",
        C::Conversion,
        "truncating conversion",
    ),
    record(12, "less", "less-than", C::Ordering, "strict ordering"),
    record(
        13,
        "less-equal",
        "less-than-or-equal",
        C::Ordering,
        "inclusive ordering",
    ),
    record(
        14,
        "greater",
        "greater-than",
        C::Ordering,
        "strict ordering",
    ),
    record(
        15,
        "greater-equal",
        "greater-than-or-equal",
        C::Ordering,
        "inclusive ordering",
    ),
    record(16, "not", "not", C::Boolean, "Boolean negation"),
    record(17, "cons", "list-prepend", C::List, "prepend a list value"),
    record(18, "car", "list-first", C::List, "read first list value"),
    record(19, "cdr", "list-rest", C::List, "read remaining list"),
    record(
        20,
        "is-empty-list",
        "is-empty-list",
        C::List,
        "empty list predicate",
    ),
    record(
        21,
        "print",
        "print",
        C::Stdio,
        "write text to standard output",
    ),
    record(22, "flush", "flush", C::Stdio, "flush standard output"),
    record(
        23,
        "read-byte",
        "read-byte",
        C::Stdio,
        "read standard input byte",
    ),
    record(
        24,
        "write-byte",
        "write-byte",
        C::Stdio,
        "write standard output byte",
    ),
    record(25, "exit", "exit", C::Control, "structured process exit"),
    record(26, "bit-and", "bit-and", C::Bit, "bitwise conjunction"),
    record(27, "bit-or", "bit-or", C::Bit, "bitwise disjunction"),
    record(
        28,
        "bit-xor",
        "bit-xor",
        C::Bit,
        "bitwise exclusive disjunction",
    ),
    record(29, "and", "and", C::Boolean, "short-circuit conjunction"),
    record(30, "or", "or", C::Boolean, "short-circuit disjunction"),
    record(
        31,
        "write-str",
        "write-string",
        C::Stdio,
        "write owned text",
    ),
    record(
        32,
        "empty-str",
        "empty-string",
        C::Text,
        "construct empty text",
    ),
    record(
        33,
        "arg-count",
        "argument-count",
        C::Arguments,
        "count process arguments",
    ),
    record(
        34,
        "arg",
        "argument-at",
        C::Arguments,
        "read process argument",
    ),
];
