use super::{record, OperationCategory as C, OperationVocabularyRecord as R};

pub(super) const RECORDS: &[R] = &[
    record(
        52,
        "stdin-handle",
        "standard-input",
        C::Resource,
        "acquire standard input",
    ),
    record(
        53,
        "sys-isatty",
        "is-terminal",
        C::Terminal,
        "terminal predicate",
    ),
    record(
        54,
        "drop-resource",
        "drop",
        C::Resource,
        "consume affine resource",
    ),
    record(
        55,
        "sys-read-byte",
        "read-resource-byte",
        C::Resource,
        "read one resource byte",
    ),
    record(
        56,
        "sys-write-byte",
        "write-resource-byte",
        C::Resource,
        "write one resource byte",
    ),
    record(
        57,
        "sys-read-into",
        "read-into",
        C::Resource,
        "read into mutable bytes",
    ),
    record(
        58,
        "sys-write-from",
        "write-from",
        C::Resource,
        "write from byte storage",
    ),
    record(
        59,
        "sys-tty-guard-save",
        "save-terminal-guard",
        C::Terminal,
        "save terminal state",
    ),
    record(
        60,
        "sys-tty-guard-clear",
        "clear-terminal-guard",
        C::Terminal,
        "clear terminal guard",
    ),
    record(
        61,
        "sys-open-read",
        "open-file-reader",
        C::File,
        "open file for reading",
    ),
    record(
        62,
        "sys-open-write",
        "open-file-writer",
        C::File,
        "open file for writing",
    ),
    record(
        63,
        "sys-open-append",
        "open-file-appender",
        C::File,
        "open file for appending",
    ),
    record(
        64,
        "sys-open-create-new",
        "create-file",
        C::File,
        "create a new file",
    ),
    record(
        65,
        "sys-open-dir",
        "open-directory",
        C::File,
        "open a directory",
    ),
    record(
        66,
        "sys-fsync",
        "sync-file",
        C::File,
        "synchronize file data",
    ),
    record(
        67,
        "sys-truncate",
        "truncate-file",
        C::File,
        "truncate a file",
    ),
    record(68, "sys-rename", "rename-path", C::File, "rename one path"),
    record(
        69,
        "sys-random-fill",
        "fill-random",
        C::Entropy,
        "fill mutable bytes",
    ),
    record(70, "sys-sha256", "sha256", C::ByteData, "compute SHA-256"),
];
