use super::{record, OperationCategory as C, OperationVocabularyRecord as R};

pub(super) const RECORDS: &[R] = &[
    record(
        35,
        "buf-new",
        "buf-new",
        C::ByteData,
        "allocate mutable bytes",
    ),
    record(36, "buf-len", "buf-length", C::ByteData, "read byte length"),
    record(37, "buf-ref", "buf-byte-at", C::ByteData, "read one byte"),
    record(38, "buf-set", "buf-set-byte", C::ByteData, "write one byte"),
    record(
        39,
        "owned-buf-new",
        "new-byte-vector",
        C::ByteData,
        "allocate affine byte vector",
    ),
    record(
        40,
        "owned-buf-len",
        "byte-slice-length",
        C::ByteData,
        "read borrowed byte length",
    ),
    record(
        41,
        "owned-buf-ref",
        "byte-slice-byte-at",
        C::ByteData,
        "read borrowed byte",
    ),
    record(
        42,
        "owned-buf-set",
        "byte-slice-mut-set-byte",
        C::ByteData,
        "write exclusive byte view",
    ),
    record(
        43,
        "buf-clone",
        "copy-buf",
        C::ByteData,
        "copy mutable bytes",
    ),
    record(
        44,
        "buf-from-str",
        "convert-string-to-buf",
        C::Conversion,
        "copy text bytes",
    ),
    record(
        45,
        "buf-to-str",
        "convert-buf-to-string",
        C::Conversion,
        "validate UTF-8 bytes",
    ),
    record(
        46,
        "path-from-str",
        "convert-string-to-path",
        C::Conversion,
        "validate text path",
    ),
    record(
        47,
        "path-from-buf",
        "convert-buf-to-path",
        C::Conversion,
        "validate byte path",
    ),
    record(
        48,
        "path-to-buf",
        "convert-path-to-buf",
        C::Conversion,
        "copy path bytes",
    ),
    record(
        49,
        "path-to-str",
        "convert-path-to-string",
        C::Conversion,
        "validate path UTF-8",
    ),
    record(
        50,
        "buf-slice",
        "copy-buf-slice",
        C::ByteData,
        "copy checked byte range",
    ),
    record(
        51,
        "buf-get-u32",
        "buf-read-u32",
        C::ByteData,
        "read big-endian u32",
    ),
    record(
        52,
        "buf-set-u32",
        "buf-write-u32",
        C::ByteData,
        "write big-endian u32",
    ),
    record(
        53,
        "str-len",
        "string-byte-length",
        C::Text,
        "read UTF-8 byte length",
    ),
    record(54, "str-ref", "string-byte-at", C::Text, "read UTF-8 byte"),
    record(
        55,
        "str-append",
        "append-string",
        C::Text,
        "append valid UTF-8 text",
    ),
    record(
        56,
        "str-slice",
        "copy-string-byte-slice",
        C::Text,
        "copy UTF-8 byte range",
    ),
    record(
        57,
        "str-from-byte",
        "convert-byte-to-string",
        C::Conversion,
        "encode byte text",
    ),
    record(
        58,
        "str-from-i64",
        "format-i64",
        C::Conversion,
        "format signed integer",
    ),
    record(
        59,
        "str-from-f64",
        "format-f64",
        C::Conversion,
        "format floating value",
    ),
];
