use super::{record, OperationCategory as C, OperationVocabularyRecord as R};

pub(super) const RECORDS: &[R] = &[
    record(
        35,
        "byte-vector-new",
        "new-byte-vector",
        C::ByteData,
        "allocate affine byte vector",
    ),
    record(
        36,
        "byte-slice-length",
        "byte-slice-length",
        C::ByteData,
        "read borrowed byte length",
    ),
    record(
        37,
        "byte-slice-byte-at",
        "byte-slice-byte-at",
        C::ByteData,
        "read borrowed byte",
    ),
    record(
        38,
        "byte-slice-mut-set-byte",
        "byte-slice-mut-set-byte",
        C::ByteData,
        "write exclusive byte view",
    ),
    record(
        39,
        "convert-string-to-bytes",
        "convert-string-to-bytes",
        C::Conversion,
        "copy text bytes",
    ),
    record(
        40,
        "convert-bytes-to-string",
        "convert-bytes-to-string",
        C::Conversion,
        "validate UTF-8 bytes",
    ),
    record(
        41,
        "path-from-str",
        "convert-string-to-path",
        C::Conversion,
        "validate text path",
    ),
    record(
        42,
        "path-from-bytes",
        "convert-bytes-to-path",
        C::Conversion,
        "validate byte path",
    ),
    record(
        43,
        "path-to-bytes",
        "convert-path-to-bytes",
        C::Conversion,
        "copy path bytes",
    ),
    record(
        44,
        "path-to-str",
        "convert-path-to-string",
        C::Conversion,
        "validate path UTF-8",
    ),
    record(
        45,
        "str-len",
        "string-byte-length",
        C::Text,
        "read UTF-8 byte length",
    ),
    record(46, "str-ref", "string-byte-at", C::Text, "read UTF-8 byte"),
    record(
        47,
        "str-append",
        "append-string",
        C::Text,
        "append valid UTF-8 text",
    ),
    record(
        48,
        "str-slice",
        "copy-string-byte-slice",
        C::Text,
        "copy UTF-8 byte range",
    ),
    record(
        49,
        "str-from-byte",
        "convert-byte-to-string",
        C::Conversion,
        "encode byte text",
    ),
    record(
        50,
        "str-from-i64",
        "format-i64",
        C::Conversion,
        "format signed integer",
    ),
    record(
        51,
        "str-from-f64",
        "format-f64",
        C::Conversion,
        "format floating value",
    ),
];
