use super::{record, OperationCategory as C, OperationVocabularyRecord as R};

pub(super) const RECORDS: &[R] = &[
    record(
        95,
        "sys-path-exists",
        "does-path-exist",
        C::File,
        "path existence predicate",
    ),
    record(
        96,
        "sys-wait-ms",
        "wait-milliseconds",
        C::Control,
        "bounded wait",
    ),
    record(
        97,
        "sys-now-ms",
        "current-time-milliseconds",
        C::Control,
        "read monotonic time",
    ),
    record(
        98,
        "sys-socket",
        "open-tcp-socket",
        C::Network,
        "open TCP socket",
    ),
    record(99, "sys-bind", "bind-tcp", C::Network, "bind TCP socket"),
    record(
        100,
        "sys-listen",
        "listen-tcp",
        C::Network,
        "listen on TCP socket",
    ),
    record(
        101,
        "sys-accept",
        "accept-tcp",
        C::Network,
        "accept TCP stream",
    ),
    record(
        102,
        "sys-recv",
        "receive-string",
        C::Network,
        "receive and validate UTF-8 text",
    ),
    record(
        103,
        "sys-send",
        "send-string",
        C::Network,
        "send UTF-8 text bytes",
    ),
    record(
        104,
        "sys-poll",
        "poll-streams",
        C::Network,
        "poll stream readiness",
    ),
    record(
        105,
        "sys-tty-get",
        "get-terminal-state",
        C::Terminal,
        "read terminal state",
    ),
    record(
        106,
        "sys-tty-set",
        "set-terminal-state",
        C::Terminal,
        "write terminal state",
    ),
    record(107, "ok", "ok", C::Variant, "construct successful result"),
    record(108, "err", "err", C::Variant, "construct failed result"),
    record(
        109,
        "is-ok",
        "is-ok",
        C::Variant,
        "successful result predicate",
    ),
    record(
        110,
        "unwrap-ok",
        "unwrap-ok",
        C::Variant,
        "read successful result",
    ),
    record(
        111,
        "unwrap-err",
        "unwrap-err",
        C::Variant,
        "read failed result",
    ),
    record(112, "some", "some", C::Variant, "construct present option"),
    record(
        113,
        "is-some",
        "is-some",
        C::Variant,
        "present option predicate",
    ),
    record(
        114,
        "unwrap-some",
        "unwrap-some",
        C::Variant,
        "read present option",
    ),
];
