use super::{record, OperationCategory as C, OperationVocabularyRecord as R};

pub(super) const RECORDS: &[R] = &[
    record(
        71,
        "sys-sqlite-open",
        "open-sqlite",
        C::Sqlite,
        "open database",
    ),
    record(
        72,
        "sys-sqlite-close",
        "close-sqlite",
        C::Sqlite,
        "close database",
    ),
    record(
        73,
        "sys-sqlite-busy-timeout",
        "set-sqlite-busy-timeout",
        C::Sqlite,
        "set busy timeout",
    ),
    record(
        74,
        "sys-sqlite-exec",
        "execute-sqlite",
        C::Sqlite,
        "execute SQL text",
    ),
    record(
        75,
        "sys-sqlite-prepare",
        "prepare-sqlite",
        C::Sqlite,
        "prepare SQL statement",
    ),
    record(
        76,
        "sys-sqlite-finalize",
        "finalize-sqlite-statement",
        C::Sqlite,
        "finalize statement",
    ),
    record(
        77,
        "sys-sqlite-reset",
        "reset-sqlite-statement",
        C::Sqlite,
        "reset statement",
    ),
    record(
        78,
        "sys-sqlite-clear-bindings",
        "clear-sqlite-bindings",
        C::Sqlite,
        "clear bindings",
    ),
    record(
        79,
        "sys-sqlite-bind-null",
        "bind-sqlite-null",
        C::Sqlite,
        "bind null",
    ),
    record(
        80,
        "sys-sqlite-bind-i64",
        "bind-sqlite-i64",
        C::Sqlite,
        "bind i64",
    ),
    record(
        81,
        "sys-sqlite-bind-f64",
        "bind-sqlite-f64",
        C::Sqlite,
        "bind f64",
    ),
    record(
        82,
        "sys-sqlite-bind-text",
        "bind-sqlite-string",
        C::Sqlite,
        "bind UTF-8 text",
    ),
    record(
        83,
        "sys-sqlite-bind-bytes",
        "bind-sqlite-bytes",
        C::Sqlite,
        "bind bytes",
    ),
    record(
        84,
        "sys-sqlite-step",
        "step-sqlite",
        C::Sqlite,
        "step statement",
    ),
    record(
        85,
        "sys-sqlite-column-count",
        "sqlite-column-count",
        C::Sqlite,
        "read column count",
    ),
    record(
        86,
        "sys-sqlite-column-type",
        "sqlite-column-type",
        C::Sqlite,
        "read column type",
    ),
    record(
        87,
        "sys-sqlite-column-i64",
        "sqlite-column-i64",
        C::Sqlite,
        "read i64 column",
    ),
    record(
        88,
        "sys-sqlite-column-f64",
        "sqlite-column-f64",
        C::Sqlite,
        "read f64 column",
    ),
    record(
        89,
        "sys-sqlite-column-text",
        "sqlite-column-string",
        C::Sqlite,
        "read text column",
    ),
    record(
        90,
        "sys-sqlite-column-bytes",
        "sqlite-column-bytes",
        C::Sqlite,
        "read byte column",
    ),
    record(
        91,
        "sys-sqlite-changes",
        "sqlite-change-count",
        C::Sqlite,
        "read change count",
    ),
    record(
        92,
        "sys-sqlite-last-insert-rowid",
        "sqlite-last-insert-rowid",
        C::Sqlite,
        "read inserted row ID",
    ),
    record(
        93,
        "sys-sqlite-extended-result-code",
        "sqlite-extended-result-code",
        C::Sqlite,
        "read result code",
    ),
    record(
        94,
        "sys-sqlite-backup",
        "backup-sqlite",
        C::Sqlite,
        "backup database",
    ),
];
