[package]
name = "lkjscript-runtime"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
lkjscript-core = { path = "../lkjscript-core" }
lkjscript-vm = { path = "../lkjscript-vm" }

[lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[lints.rust]
unsafe_code = "forbid"

[workspace]
