[package]
name = "lkjscript-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
lkjscript-contracts = { path = "../lkjscript-contracts" }
lkjscript-core = { path = "../lkjscript-core" }
lkjscript-host = { path = "../lkjscript-host" }
lkjscript-vm = { path = "../lkjscript-vm" }

[lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[lints.rust]
unsafe_code = "forbid"
