use super::registry::{
    RegistrySnapshot, contract_descriptors, diagnostic_descriptors, enum_name,
    exit_status_descriptors, operation_descriptors, registry_snapshot,
};
use super::schema::{protocol_schema_bytes, protocol_schema_digest};
use serde_json::json;
use std::fmt::Write as _;

const GENERATOR_COMMAND: &str = "lkjscript capabilities --generate-docs docs/generated";

#[derive(Clone, Debug)]
pub struct GeneratedDocument {
    pub relative_path: &'static str,
    pub bytes: Vec<u8>,
}

pub fn generated_documents() -> Result<Vec<GeneratedDocument>, String> {
    let schema_digest = protocol_schema_digest()?;
    let snapshot = registry_snapshot(&schema_digest)?;
    Ok(vec![
        GeneratedDocument {
            relative_path: "contracts.md",
            bytes: contracts_markdown(&snapshot).into_bytes(),
        },
        GeneratedDocument {
            relative_path: "protocol.schema.json",
            bytes: protocol_schema_bytes()?,
        },
        GeneratedDocument {
            relative_path: "operations.md",
            bytes: operations_markdown(&snapshot).into_bytes(),
        },
        GeneratedDocument {
            relative_path: "diagnostics.md",
            bytes: diagnostics_markdown(&snapshot).into_bytes(),
        },
        GeneratedDocument {
            relative_path: "manifest.json",
            bytes: manifest_bytes(&snapshot)?,
        },
    ])
}

fn generated_header(snapshot: &RegistrySnapshot) -> String {
    format!(
        "<!-- Generated by `{GENERATOR_COMMAND}`. Do not edit. Registry `{}`; schema `{}`. -->\n\n",
        snapshot.digest, snapshot.manifest.schema_digest
    )
}

fn contracts_markdown(snapshot: &RegistrySnapshot) -> String {
    let mut output = generated_header(snapshot);
    output.push_str("# Current executable contracts\n\n");
    output.push_str("| Key | Identity | Version | Authority | Predecessor |\n");
    output.push_str("|---|---|---:|---|---|\n");
    for contract in contract_descriptors() {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} | `{}` | `{}` |",
            enum_name(contract.key),
            contract.identity,
            contract.version,
            enum_name(contract.authority),
            enum_name(contract.predecessor_policy)
        );
    }
    output
}

fn operations_markdown(snapshot: &RegistrySnapshot) -> String {
    let mut output = generated_header(snapshot);
    output.push_str("# Public operations\n\n");
    output
        .push_str("| Operation | Request schema | Response schema | Authority effect | Usage |\n");
    output.push_str("|---|---|---|---|---|\n");
    for operation in operation_descriptors() {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | `{}` | `{}` | `{}` |",
            operation.operation.name(),
            operation.request_schema.name(),
            operation.response_schema.name(),
            enum_name(operation.authority_effect),
            operation.usage
        );
    }
    output
}

fn diagnostics_markdown(snapshot: &RegistrySnapshot) -> String {
    let mut output = generated_header(snapshot);
    output.push_str("# Protocol diagnostics and exit statuses\n\n");
    output.push_str("| Code | Class | Stable meaning | Retry guidance |\n");
    output.push_str("|---|---|---|---|\n");
    for diagnostic in diagnostic_descriptors() {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} | {} |",
            diagnostic.code,
            enum_name(diagnostic.class),
            diagnostic.meaning,
            diagnostic.retry
        );
    }
    output.push_str("\n| Exit | Meaning |\n|---:|---|\n");
    for status in exit_status_descriptors() {
        let _ = writeln!(output, "| {} | {} |", status.status, status.meaning);
    }
    output
}

fn manifest_bytes(snapshot: &RegistrySnapshot) -> Result<Vec<u8>, String> {
    let value = json!({
        "generated": true,
        "generator": GENERATOR_COMMAND,
        "registry_digest": snapshot.digest,
        "manifest": snapshot.manifest,
    });
    let mut bytes = serde_json::to_vec_pretty(&value)
        .map_err(|error| format!("generated manifest could not be encoded: {error}"))?;
    bytes.push(b'\n');
    Ok(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_documents_are_unique_and_repeatable() {
        let first = generated_documents().expect("generated documents");
        let second = generated_documents().expect("generated documents");
        assert_eq!(first.len(), second.len());
        for (left, right) in first.iter().zip(second.iter()) {
            assert_eq!(left.relative_path, right.relative_path);
            assert_eq!(left.bytes, right.bytes);
            assert!(left.bytes.ends_with(b"\n"));
        }
    }

    #[test]
    fn checked_in_generated_documents_match_executable_truth() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/generated");
        for document in generated_documents().expect("generated documents") {
            let path = root.join(document.relative_path);
            assert_eq!(
                std::fs::read(&path).expect("checked-in generated document"),
                document.bytes,
                "{} is stale; run {GENERATOR_COMMAND}",
                path.display()
            );
        }
    }
}
