use super::registry::{
    CapabilitiesSnapshot, RegistrySection, capabilities_snapshot, diagnostic_class_name,
    diagnostic_descriptors, exit_status_descriptors, operation_descriptors,
};
use crate::platform::builtin_discovery::inspect_builtin_owner;
use crate::platform::builtin_standard::BuiltinStandard;
use crate::platform::control::render_record;
use crate::platform::kernel::{OwnerKey, OwnerKind, PackageInterfaceRecord};
use crate::platform::project_creation::ProjectTemplate;
use std::fmt::Write as _;

const GENERATOR_COMMAND: &str = "lkjscript capabilities --generate-docs docs/generated";

#[derive(Clone, Debug)]
pub struct GeneratedDocument {
    pub relative_path: &'static str,
    pub bytes: Vec<u8>,
}

pub fn generated_documents() -> Result<Vec<GeneratedDocument>, String> {
    let snapshot = capabilities_snapshot()?;
    Ok(vec![
        GeneratedDocument {
            relative_path: "operations.md",
            bytes: operations_markdown(&snapshot)?.into_bytes(),
        },
        GeneratedDocument {
            relative_path: "diagnostics.md",
            bytes: diagnostics_markdown(&snapshot).into_bytes(),
        },
        GeneratedDocument {
            relative_path: "change-grammar.md",
            bytes: registry_sections_markdown(
                &snapshot,
                "Compact change grammar",
                &[
                    RegistrySection::Change,
                    RegistrySection::Type,
                    RegistrySection::Expression,
                ],
            )?
            .into_bytes(),
        },
        GeneratedDocument {
            relative_path: "function-definition.md",
            bytes: registry_sections_markdown(
                &snapshot,
                "Revision-pinned function definition projection",
                &[RegistrySection::Inspection],
            )?
            .into_bytes(),
        },
        GeneratedDocument {
            relative_path: "deployment.md",
            bytes: registry_sections_markdown(
                &snapshot,
                "Deployment descriptor schema",
                &[RegistrySection::Deployment],
            )?
            .into_bytes(),
        },
        GeneratedDocument {
            relative_path: "builtin-standard.md",
            bytes: builtin_standard_markdown(&snapshot)?.into_bytes(),
        },
        GeneratedDocument {
            relative_path: "stateful-http-authoring.md",
            bytes: stateful_http_walkthrough(&snapshot)?.into_bytes(),
        },
        GeneratedDocument {
            relative_path: "nostr-relay-info-authoring.md",
            bytes: nostr_relay_info_walkthrough(&snapshot)?.into_bytes(),
        },
    ])
}

fn generated_header(snapshot: &CapabilitiesSnapshot) -> String {
    format!(
        "<!-- Generated by `{GENERATOR_COMMAND}`. Do not edit. {} {} capabilities `{}`. -->\n\n",
        snapshot.product_name, snapshot.product_version, snapshot.digest
    )
}

fn operations_markdown(snapshot: &CapabilitiesSnapshot) -> Result<String, String> {
    let mut output = generated_header(snapshot);
    output.push_str("# Public operations\n\n");
    output.push_str("| Operation | Request model | Response model | Authority effect | Usage |\n");
    output.push_str("|---|---|---|---|---|\n");
    for operation in operation_descriptors() {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | `{}` | `{}` | `{}` |",
            operation.operation.name(),
            operation.request_model.name(),
            operation.response_model.name(),
            operation.authority_effect.name(),
            operation.usage
        );
    }
    output.push_str("\n## Project templates\n\n");
    output.push_str(
        "| Template | Purpose | Runner | Starter deployment | Recommended artifact output |\n",
    );
    output.push_str("|---|---|---|---|---|\n");
    for template in ProjectTemplate::ALL {
        let _ = writeln!(
            output,
            "| `{}` | {} | `{}` | `{}` | `{}` |",
            template.name(),
            template.purpose(),
            template.runner(),
            template.emits_deployment(),
            template.recommended_artifact_output().unwrap_or("none")
        );
    }
    let execution = snapshot
        .section(RegistrySection::Runners)
        .ok_or_else(|| "generated operations lack runner observations".to_owned())?;
    output.push_str("\n## Execution observations\n\n```text\n");
    output.push_str(
        std::str::from_utf8(&execution.bytes)
            .map_err(|_| "runner observations are not UTF-8".to_owned())?,
    );
    output.push_str("```\n");
    Ok(output)
}

fn diagnostics_markdown(snapshot: &CapabilitiesSnapshot) -> String {
    let mut output = generated_header(snapshot);
    output.push_str("# Protocol diagnostics and exit statuses\n\n");
    output.push_str("| Code | Class | Stable meaning | Retry guidance |\n");
    output.push_str("|---|---|---|---|\n");
    for diagnostic in diagnostic_descriptors() {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} | {} |",
            diagnostic.code,
            diagnostic_class_name(diagnostic.class),
            diagnostic.meaning,
            diagnostic.retry
        );
    }
    output.push_str("\n| Exit | Meaning |\n|---:|---|\n");
    for status in exit_status_descriptors() {
        let _ = writeln!(output, "| {} | {} |", status.status, status.meaning);
    }
    output
}

fn registry_sections_markdown(
    snapshot: &CapabilitiesSnapshot,
    title: &str,
    sections: &[RegistrySection],
) -> Result<String, String> {
    let mut output = generated_header(snapshot);
    let _ = writeln!(output, "# {title}\n");
    output.push_str(
        "The following compact records are the executable-owned current public capability.\n\n```text\n",
    );
    for section in sections {
        let value = snapshot
            .section(*section)
            .ok_or_else(|| format!("generated document is missing '{}'", section.name()))?;
        output.push_str(std::str::from_utf8(&value.bytes).map_err(|_| {
            format!(
                "capability section '{}' is not canonical UTF-8",
                section.name()
            )
        })?);
    }
    output.push_str("```\n");
    Ok(output)
}

fn builtin_standard_markdown(snapshot: &CapabilitiesSnapshot) -> Result<String, String> {
    let standard = BuiltinStandard::load().map_err(|error| error.to_string())?;
    let mut output = generated_header(snapshot);
    output.push_str("# Built-in standard package public interface\n\n");
    let _ = writeln!(
        output,
        "Package `{}` at exact package revision `{}`.\n",
        standard.package, standard.package_revision
    );
    output.push_str(
        "The records below are implementation-free public interface projections. Exact `reference` values are accepted by compact change records.\n\n```text\n",
    );
    for (owner, value) in &standard.interface_owners {
        if !matches!(value.record, PackageInterfaceRecord::Declaration(_)) {
            continue;
        }
        for record in inspect_builtin_owner(standard, value.record.header().kind, *owner)
            .map_err(|error| error.to_string())?
        {
            output.push_str(&record.render().map_err(|error| error.to_string())?);
        }
    }
    output.push_str("```\n");
    Ok(output)
}

fn stateful_http_walkthrough(snapshot: &CapabilitiesSnapshot) -> Result<String, String> {
    let standard = BuiltinStandard::load().map_err(|error| error.to_string())?;
    let exact = |kind: OwnerKind, name: &str, parent: Option<OwnerKey>| {
        standard
            .interface_owners
            .iter()
            .find_map(|(owner, value)| {
                (value.record.header().kind == kind
                    && package_owner_name(&value.record) == name
                    && package_owner_parent(&value.record) == parent)
                    .then(|| format!("{}/{}", standard.package, owner))
            })
            .ok_or_else(|| format!("built-in standard lacks exact {kind:?} '{name}'"))
    };
    let byte_stream_owner = exact(OwnerKind::Interface, "ByteStream", None)?;
    let byte_stream_id = parse_reference_owner(&byte_stream_owner)?;
    let data_owner = exact(OwnerKind::Interface, "DataStore", None)?;
    let data_id = parse_reference_owner(&data_owner)?;
    let mut output = generated_header(snapshot);
    output.push_str("# Stateful HTTP authoring walkthrough\n\n");
    output.push_str(
        "This is a generated composition guide, not a second authoring authority. Start from `new --template minimal`, discover the exact built-in binding and owner references, export and stage that immutable transport, and submit dependency, component, requirements, function-backed HTTP port, target, and application policy in one bounded compact request. Secret values never enter semantic records or this guide.\n\n",
    );
    output.push_str("## Current exact capability and declaration references\n\n```text\n");
    let walkthrough_records = [
        (
            "walkthrough.interface",
            vec![
                ("name", "byte-stream".to_owned()),
                ("reference", byte_stream_owner.clone()),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "read-all".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "read-all", Some(byte_stream_id))?,
                ),
            ],
        ),
        (
            "walkthrough.interface",
            vec![
                ("name", "data".to_owned()),
                ("reference", data_owner.clone()),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "schema-read".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "schema-read", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "transaction".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "transaction", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "schema-set".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "schema-set", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "get".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "get", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "scan".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "scan", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "put".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "put", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.operation",
            vec![
                ("name", "delete".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::Operation, "delete", Some(data_id))?,
                ),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "json-decode-or".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::External, "json-decode-or", None)?,
                ),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "json-encode".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::External, "json-encode", None)?,
                ),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "list-length".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::External, "list-length", None)?,
                ),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "list-get".to_owned()),
                ("reference", exact(OwnerKind::External, "list-get", None)?),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "data-key-part".to_owned()),
                ("reference", exact(OwnerKind::Variant, "DataKeyPart", None)?),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "data-entry".to_owned()),
                ("reference", exact(OwnerKind::Record, "DataEntry", None)?),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "data-encode".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::External, "data-encode", None)?,
                ),
            ],
        ),
        (
            "walkthrough.declaration",
            vec![
                ("name", "data-decode-or".to_owned()),
                (
                    "reference",
                    exact(OwnerKind::External, "data-decode-or", None)?,
                ),
            ],
        ),
    ];
    for (operation, fields) in walkthrough_records {
        let fields = fields
            .iter()
            .map(|(name, value)| (*name, value.as_str()))
            .collect::<Vec<_>>();
        output.push_str(&render_record(operation, &fields).map_err(|error| error.to_string())?);
    }
    output.push_str("```\n\n## Composition\n\n```text\n");
    for (operation, fields) in [
        (
            "walkthrough.bootstrap",
            vec![
                ("template", "minimal"),
                ("owners", "0"),
                ("dependencies", "0"),
            ],
        ),
        (
            "walkthrough.dependency",
            vec![
                ("operation", "add.dependency"),
                ("binding", "package+semantic-revision+package-revision"),
                ("transport", "builtin-export+dependency-stage"),
            ],
        ),
        (
            "walkthrough.topology",
            vec![
                (
                    "operations",
                    "create.component+add.requirement+add.port+create.target+add.http-route",
                ),
                ("port", "function-backed"),
                ("route", "GET+/"),
                ("runner", "http"),
            ],
        ),
        (
            "walkthrough.request",
            vec![
                ("parameter", "$request"),
                ("projection", "method,path,query_parameters,headers,body"),
            ],
        ),
        (
            "walkthrough.body",
            vec![
                ("form", "field+capability-call"),
                ("stream-operation", "read-all"),
                ("maximum", "65536"),
                ("unit", "bytes"),
            ],
        ),
        (
            "walkthrough.json",
            vec![
                ("form", "call+type.argument+field"),
                ("decoder", "json-decode-or"),
                ("strict", "duplicate,trailing,shape reject"),
                ("encoder", "json-encode"),
            ],
        ),
        (
            "walkthrough.data",
            vec![
                ("form", "transaction+capability-call"),
                ("operations", "schema-read,schema-set,get,scan,put,delete"),
                ("keys", "static-space+typed-key-parts"),
                ("values", "canonical-typed-data-bytes"),
            ],
        ),
        (
            "walkthrough.response",
            vec![
                ("form", "structural-record"),
                (
                    "fields",
                    "status:i64,headers:list<{name:text,value:bytes}>,body:bytes",
                ),
                ("policy", "graph-owned"),
            ],
        ),
        (
            "walkthrough.grant",
            vec![
                ("requirement", "data"),
                ("adapter", "data"),
                ("root", "deployment-relative-local-directory"),
                ("secret-value", "none"),
                ("limits", "keys,values,transactions,scans,live-resources"),
            ],
        ),
    ] {
        output.push_str(&render_record(operation, &fields).map_err(|error| error.to_string())?);
    }
    output.push_str("```\n\nThe transport stage must leave semantic `HEAD` unchanged. Use reviewed `change plan`, export and decode the complete logical plan, then apply the exact plan token and idempotently re-prepare it. Run `check`, clean/incremental `build`, and `serve --deployment` only after publication. Runtime work reads the artifact and cannot advance project authority.\n");
    Ok(output)
}

fn nostr_relay_info_walkthrough(snapshot: &CapabilitiesSnapshot) -> Result<String, String> {
    let standard = BuiltinStandard::load().map_err(|error| error.to_string())?;
    let exact = |kind: OwnerKind, name: &str, parent: Option<OwnerKey>| {
        standard
            .interface_owners
            .iter()
            .find_map(|(owner, value)| {
                (value.record.header().kind == kind
                    && package_owner_name(&value.record) == name
                    && package_owner_parent(&value.record) == parent)
                    .then(|| format!("{}/{}", standard.package, owner))
            })
            .ok_or_else(|| format!("built-in standard lacks exact {kind:?} '{name}'"))
    };
    let client_owner = exact(OwnerKind::Interface, "HttpClient", None)?;
    let client_id = parse_reference_owner(&client_owner)?;
    let get_owner = exact(OwnerKind::Operation, "get", Some(client_id))?;
    let template = ProjectTemplate::NostrRelayInfo;
    let defaults = crate::platform::http_client::HttpClientLimits::default();
    let mut output = generated_header(snapshot);
    output.push_str("# Nostr relay-information authoring walkthrough\n\n");
    output.push_str(
        "This generated composition guide describes the closed NIP-11 information slice. The typed graph selects only request headers and response policy; one strict deployment grant owns the immutable endpoint, address class, TLS trust, and transport limits. It is not a second authoring authority and does not implement WebSocket or NIP-01.\n\n",
    );
    output.push_str("## Exact recipe and capability\n\n```text\n");
    for (operation, fields) in [
        (
            "relay-info.recipe",
            vec![
                ("template", template.name().to_owned()),
                (
                    "usage",
                    "new DEST --template nostr-relay-info [--name NAME] --relay-url URL".to_owned(),
                ),
                (
                    "artifact",
                    template
                        .recommended_artifact_output()
                        .unwrap_or("none")
                        .to_owned(),
                ),
                ("runner", template.runner().to_owned()),
            ],
        ),
        (
            "relay-info.interface",
            vec![
                ("name", "HttpClient".to_owned()),
                ("reference", client_owner),
            ],
        ),
        (
            "relay-info.operation",
            vec![
                ("name", "get".to_owned()),
                ("reference", get_owner),
                (
                    "argument",
                    "ordered-list<{name:text,value:bytes}>".to_owned(),
                ),
                (
                    "result",
                    "{status:i64,headers:list<{name:text,value:bytes}>,body:bytes}".to_owned(),
                ),
            ],
        ),
    ] {
        let fields = fields
            .iter()
            .map(|(name, value)| (*name, value.as_str()))
            .collect::<Vec<_>>();
        output.push_str(&render_record(operation, &fields).map_err(|error| error.to_string())?);
    }
    output.push_str("```\n\n## Closed behavior\n\n```text\n");
    let default_request_headers = defaults.maximum_request_headers.to_string();
    let default_request_header_bytes = defaults.maximum_request_header_bytes.to_string();
    let default_response_headers = defaults.maximum_response_headers.to_string();
    let default_response_header_bytes = defaults.maximum_response_header_bytes.to_string();
    let default_response_body_bytes = defaults.maximum_response_body_bytes.to_string();
    let default_dns_results = defaults.maximum_dns_results.to_string();
    let default_concurrent_requests = defaults.maximum_concurrent_requests.to_string();
    let default_connection_milliseconds = defaults.connection_timeout_milliseconds.to_string();
    let default_total_milliseconds = defaults.total_timeout_milliseconds.to_string();
    let default_cleanup_milliseconds = defaults.cleanup_timeout_milliseconds.to_string();
    for (operation, fields) in [
        (
            "relay-info.normalization",
            vec![
                ("secure", "wss->https,https->https"),
                ("development", "ws->http,http->http"),
                ("plaintext", "loopback-only"),
                ("reject", "userinfo,query,fragment,noncanonical-authority"),
            ],
        ),
        (
            "relay-info.request",
            vec![
                ("inbound", "GET /relay-info"),
                ("outbound", "GET exact-deployment-endpoint"),
                ("accept", "application/nostr+json"),
                ("body", "none"),
            ],
        ),
        (
            "relay-info.response",
            vec![
                (
                    "success",
                    "status=200+base-media-type=application/nostr+json",
                ),
                ("body", "bounded-byte-exact"),
                ("failure", "local-status=502 body=bad-gateway"),
                ("remote-detail", "redacted"),
            ],
        ),
        (
            "relay-info.transport",
            vec![
                ("protocol", "http/1.1"),
                ("redirects", "never"),
                ("retries", "never"),
                ("decompression", "never"),
                ("proxy", "none"),
                ("credentials", "none"),
            ],
        ),
        (
            "relay-info.default-limits",
            vec![
                ("request-headers", default_request_headers.as_str()),
                (
                    "request-header-bytes",
                    default_request_header_bytes.as_str(),
                ),
                ("response-headers", default_response_headers.as_str()),
                (
                    "response-header-bytes",
                    default_response_header_bytes.as_str(),
                ),
                ("response-body-bytes", default_response_body_bytes.as_str()),
                ("dns-results", default_dns_results.as_str()),
                ("concurrent-requests", default_concurrent_requests.as_str()),
                (
                    "connection-milliseconds",
                    default_connection_milliseconds.as_str(),
                ),
                ("total-milliseconds", default_total_milliseconds.as_str()),
                (
                    "cleanup-milliseconds",
                    default_cleanup_milliseconds.as_str(),
                ),
            ],
        ),
        (
            "relay-info.lifecycle",
            vec![
                ("inspect", "status+query+inspect"),
                ("verify", "check"),
                ("derive", "build --output generated/application.lkja"),
                ("execute", "serve --deployment service.deployment.json"),
            ],
        ),
    ] {
        output.push_str(&render_record(operation, &fields).map_err(|error| error.to_string())?);
    }
    output.push_str("```\n\nRead `deployment.md` for the executable-owned strict adapter schema and global maxima. Read the normative outbound-client specification for DNS/address classification, TLS trust, cancellation, cleanup, and security nonclaims.\n");
    Ok(output)
}

fn parse_reference_owner(reference: &str) -> Result<OwnerKey, String> {
    reference
        .split_once('/')
        .ok_or_else(|| format!("exact reference '{reference}' has no owner"))?
        .1
        .parse()
        .map_err(|error: crate::platform::diagnostic::Diagnostic| error.to_string())
}

fn package_owner_name(record: &PackageInterfaceRecord) -> &str {
    match record {
        PackageInterfaceRecord::Declaration(value) => value.name.as_str(),
        PackageInterfaceRecord::TypeParameter(value) => value.name.as_str(),
        PackageInterfaceRecord::Field(value) => value.name.as_str(),
        PackageInterfaceRecord::Case(value) => value.name.as_str(),
        PackageInterfaceRecord::Operation(value) => value.name.as_str(),
        PackageInterfaceRecord::Parameter(value) => value.name.as_str(),
        PackageInterfaceRecord::Requirement(value) => value.name.as_str(),
        PackageInterfaceRecord::Port(value) => value.name.as_str(),
    }
}

fn package_owner_parent(record: &PackageInterfaceRecord) -> Option<OwnerKey> {
    match record {
        PackageInterfaceRecord::Declaration(_) => None,
        PackageInterfaceRecord::TypeParameter(value) => {
            Some(OwnerKey::Declaration(value.declaration))
        }
        PackageInterfaceRecord::Field(value) => Some(OwnerKey::Declaration(value.declaration)),
        PackageInterfaceRecord::Case(value) => Some(OwnerKey::Declaration(value.declaration)),
        PackageInterfaceRecord::Operation(value) => Some(OwnerKey::Declaration(value.declaration)),
        PackageInterfaceRecord::Parameter(value) => Some(match value.parent {
            crate::platform::kernel::ParameterParent::Function(declaration) => {
                OwnerKey::Declaration(declaration)
            }
            crate::platform::kernel::ParameterParent::Operation(operation) => {
                OwnerKey::Operation(operation)
            }
        }),
        PackageInterfaceRecord::Requirement(value) => {
            Some(OwnerKey::Declaration(value.declaration))
        }
        PackageInterfaceRecord::Port(value) => Some(OwnerKey::Declaration(value.declaration)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_documents_are_unique_and_repeatable() {
        let first = generated_documents().expect("generated documents");
        let second = generated_documents().expect("generated documents");
        assert_eq!(first.len(), 8);
        assert_eq!(first.len(), second.len());
        for (left, right) in first.iter().zip(second.iter()) {
            assert_eq!(left.relative_path, right.relative_path);
            assert_eq!(left.bytes, right.bytes);
            assert!(left.bytes.ends_with(b"\n"));
        }
        let operations = first
            .iter()
            .find(|document| document.relative_path == "operations.md")
            .expect("generated operations document");
        let operations = std::str::from_utf8(&operations.bytes).expect("UTF-8 operations document");
        for template in ProjectTemplate::ALL {
            assert!(operations.contains(&format!("| `{}` |", template.name())));
        }
    }

    #[test]
    fn checked_in_generated_documents_match_executable_truth() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/generated");
        for document in generated_documents().expect("generated documents") {
            let path = root.join(document.relative_path);
            assert_eq!(
                std::fs::read(&path).expect("checked-in generated document"),
                document.bytes,
                "{} is stale; run {GENERATOR_COMMAND}",
                path.display()
            );
        }
        for removed in ["contracts.md", "protocol.schema.json", "manifest.json"] {
            assert!(
                !root.join(removed).exists(),
                "obsolete generated output must remain deleted"
            );
        }
    }
}
