//! Executable ownership of public and stored contract discovery.

mod generated;
pub(crate) mod registry;

pub use generated::{GeneratedDocument, generated_documents};
pub use registry::{
    AuthorityEffect, BudgetProfile, CLI_CONTRACT_VERSION, CapabilitiesSnapshot, ContractAuthority,
    ContractDescriptor, ContractKey, ContractStability, ControlModel, DiagnosticDescriptor,
    ExitStatusDescriptor, FUNCTION_DEFINITION_DEFAULT_ITEMS,
    FUNCTION_DEFINITION_DEFAULT_OUTPUT_BYTES, FUNCTION_DEFINITION_PROJECTION_CONTRACT_IDENTITY,
    FUNCTION_DEFINITION_PROJECTION_CONTRACT_VERSION, LimitClass, LimitDescriptor, LimitUnit,
    MAXIMUM_CLI_RESPONSE_BYTES, MAXIMUM_CLI_RESPONSE_RECORDS,
    MAXIMUM_FUNCTION_DEFINITION_BODY_RECORDS, MAXIMUM_FUNCTION_DEFINITION_CANONICAL_RECORD_READS,
    MAXIMUM_FUNCTION_DEFINITION_CONTINUATION_BYTES, MAXIMUM_FUNCTION_DEFINITION_DEPTH,
    MAXIMUM_FUNCTION_DEFINITION_EDGES, MAXIMUM_FUNCTION_DEFINITION_FACT_READS,
    MAXIMUM_FUNCTION_DEFINITION_ITEMS, MAXIMUM_FUNCTION_DEFINITION_LITERAL_FRAGMENT_BYTES,
    MAXIMUM_FUNCTION_DEFINITION_LOGICAL_BYTES, MAXIMUM_FUNCTION_DEFINITION_MAP_BYTES,
    MAXIMUM_FUNCTION_DEFINITION_MAP_ENTRIES, MAXIMUM_FUNCTION_DEFINITION_MAP_PAGES,
    MAXIMUM_FUNCTION_DEFINITION_OUTPUT_BYTES, MAXIMUM_FUNCTION_DEFINITION_OWNERSHIP_READS,
    MAXIMUM_FUNCTION_DEFINITION_STORE_BYTES, MAXIMUM_FUNCTION_DEFINITION_STORE_OBJECTS,
    MAXIMUM_FUNCTION_EXTRACTION_CAPTURE_USES, MAXIMUM_FUNCTION_EXTRACTION_CAPTURES,
    MAXIMUM_FUNCTION_EXTRACTION_CHANGED_OWNERS, MAXIMUM_FUNCTION_EXTRACTION_GENERATED_OWNERS,
    MAXIMUM_FUNCTION_EXTRACTION_MOVED_OWNERS, MAXIMUM_FUNCTION_EXTRACTION_PRESERVED_OWNERS,
    MAXIMUM_FUNCTION_EXTRACTION_REQUIREMENTS, MAXIMUM_TRANSACTION_REQUEST_BYTES,
    MINIMUM_FUNCTION_DEFINITION_OUTPUT_BYTES, OperationDescriptor, OverridePolicy,
    PredecessorPolicy, ProjectRequirement, PublicOperation, REGISTRY_CONTRACT_IDENTITY,
    REGISTRY_CONTRACT_VERSION, RegistrySection, RegistrySectionSnapshot, RegistrySnapshot,
    capabilities_snapshot, contract_descriptors, diagnostic_class_name, diagnostic_descriptors,
    exit_status_descriptors, exit_status_for, limit_descriptors, nonclaims, operation_descriptors,
    operation_record, outcome_exit_status, registry_snapshot,
};
pub(crate) use registry::{
    FUNCTION_DEFINITION_CONTINUATION_INTEGRITY_DOMAIN, FUNCTION_DEFINITION_CONTINUATION_MAGIC_TEXT,
    FUNCTION_DEFINITION_LOGICAL_DIGEST_DOMAIN, FUNCTION_DEFINITION_RECORD_KEY_DOMAIN,
    FUNCTION_DEFINITION_RESPONSE_FIELDS,
};
