mod branches;
mod calls;
mod compact_places;
mod compact_values;
mod constants;
mod copies;
mod effects;
mod forwarding;
mod order;
mod pipeline;
mod reachability;

pub use branches::simplify_branches;
pub use calls::direct_call_resolution;
pub(crate) use compact_places::*;
pub(crate) use compact_values::*;
pub use constants::constant_fold_and_propagate;
pub use copies::copy_propagate;
pub use effects::effect_aware_dce;
pub(crate) use effects::*;
pub use forwarding::empty_block_forwarding;
pub use order::canonical_block_order;
pub(crate) use order::*;
pub use pipeline::normalize_baseline;
pub(crate) use pipeline::*;
pub use reachability::unreachable_blocks;
