#![allow(clippy::expect_used, clippy::panic)]
mod evaluator;
mod fixtures;
mod optimization_budgets;
mod optimization_certificates;
mod optimization_checker;
mod optimization_dominance;
mod ownership_aliases;
mod ownership_budgets;
mod ownership_edges;
mod ownership_facts;
mod ownership_paths;
mod passes;
mod verification_generics;
mod verification_shape;
mod verification_traits;
