[package]
name = "lkjscript-database"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
lkjscript-host = { path = "../lkjscript-host" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
