use super::templates_runtime::runtime_state;
use super::MemoryObligation;

pub(super) const RUNTIME: &[MemoryObligation] = &[
    runtime_state(
        "evaluator-state",
        "recursive EvalValue plus deterministic unique byte owners and loans",
        "validated unique owners and shared or exclusive byte loans",
        "one evaluation",
        "deterministic cumulative accounting",
        "not applicable",
        "value identity for immutable bytes and unique owner identity for mutation",
        "Rust-owned evaluator graph",
        "abstract unique, borrow, region, share and pool semantics",
        "deterministic abstract owner cleanup",
        "independent SSA evaluator",
        "evaluator/VM differential and ownership budget suites",
    ),
    runtime_state(
        "native-frame",
        "registered generated frame plus typed value homes",
        "active frame chain",
        "generated call",
        "typed frame-resident values",
        "none",
        "frame identity",
        "native stack plus sys chain",
        "typed owners, borrows, regions, release and resource cleanup metadata",
        "unregister on every structured outcome",
        "native encoder and sys executable state",
        "native active frames, outcomes and image integrity suites",
    ),
    runtime_state(
        "resource-table",
        "typed host resource entries indexed by monotonic tokens",
        "one affine owner plus borrowed standard input",
        "VM session or explicit close",
        "none",
        "none",
        "external resource identity",
        "VM-owned resource table",
        "typed generational slots",
        "exact close/drop then slot generation invalidation",
        "VM host providers",
        "resource kind, close, stale token and host operation suites",
    ),
    runtime_state(
        "returned-value",
        "OwnedValue plus canonical structural and list snapshots",
        "key-free owned structural images and list tables",
        "host wrapper",
        "none",
        "none",
        "source value identity only",
        "owned return wrapper",
        "unique graph, region owner, sealed region, eligible shared roots, pool owner, static",
        "drop explicit returned owner",
        "VM into_owned and JIT snapshot",
        "returned structural ownership and cross-engine result suites",
    ),
    runtime_state(
        "vm-frame",
        "stack range plus frame metadata",
        "values carry inline scalars or invocation-local structural keys",
        "bytecode call",
        "typed operand and local values through the VM stack",
        "none",
        "frame identity not observable",
        "VM stack",
        "typed inline and owner slots with cleanup blocks",
        "pop exact owners and cleanup obligations",
        "validated bytecode dispatch",
        "tail-call, frame limit and structured outcome suites",
    ),
];
