use super::templates::{inline, traced};
use super::MemoryObligation;

pub(super) const STRUCTURAL: &[MemoryObligation] = &[
    inline(
        "builtin",
        "bytecode validation and operation registry",
        "validated operation identity",
        "validated bytecode operation ID; no HeapObj",
        "bytecode operation dispatch; no runtime allocator",
        "operation registry and bytecode validation suites",
    ),
    inline(
        "closure",
        "source, HIR, SSA, bytecode, VM",
        "capture-free function value; captured closure graphs unsupported",
        "Value::Function with validated prototype ID",
        "validated zero-capture function references and calls",
        "closure call, validation, recursion and tail-call suites",
    ),
    traced(
        "enum",
        "nominal immutable algebraic value",
        "HeapObj::Enum",
        "immutable",
        "active initialized payload",
        "not constructible in validated source",
        "none",
        "layout plus active payload",
        "inline, stack, caller-destination, unique, region, sealed region, eligible shared-node",
        "enum constructors in evaluator, VM and native",
        "enum differential and malformed layout suites",
    ),
    traced(
        "error",
        "typed immutable error enum",
        "HeapObj::Enum and scalar payloads",
        "immutable",
        "active payload",
        "not constructible in validated source",
        "none",
        "small ADT",
        "inline niche, stack, caller-destination, unique, region",
        "numeric and host result constructors",
        "typed numeric, UTF-8 and system result suites",
    ),
    traced(
        "list",
        "persistent immutable list",
        "empty immediate or HeapObj::Pair",
        "immutable",
        "head and tail",
        "not constructible in validated source",
        "none",
        "pair per element",
        "unique list, borrowed traversal, region, sealed region, copying, eligible shared tails",
        "list constructors and standard library",
        "list equality, limits and corpus suites",
    ),
    traced(
        "option",
        "generic immutable enum",
        "empty immediate or HeapObj::Enum",
        "immutable",
        "active payload",
        "not constructible in validated source",
        "none",
        "small ADT",
        "inline niche, stack, caller-destination, unique, region, sealed region",
        "generic enum constructor",
        "Option evaluator/VM/native and malformed suites",
    ),
    traced(
        "pair",
        "list node",
        "HeapObj::Pair",
        "immutable",
        "car and cdr",
        "runtime model permits graph edges; source mutation absent",
        "none",
        "two values",
        "unique, region, sealed region, eligible acyclic shared-node",
        "list construction",
        "collection, equality, roots and snapshot suites",
    ),
    traced(
        "product",
        "nominal immutable product",
        "HeapObj::Product",
        "immutable",
        "all fields",
        "not constructible in validated source",
        "none",
        "layout plus fields",
        "inline, stack, caller-destination, unique, region, sealed region, eligible shared-node",
        "product construction in evaluator, VM and native",
        "product differential and heap layout suites",
    ),
    traced(
        "result",
        "generic immutable enum",
        "HeapObj::Enum",
        "immutable",
        "active payload",
        "not constructible in validated source",
        "none",
        "small ADT",
        "inline niche, stack, caller-destination, unique, region, sealed region",
        "generic enum and host result constructors",
        "Result evaluator/VM/native and host suites",
    ),
    inline(
        "static-function",
        "HIR and SSA direct function identity",
        "static function",
        "FunctionId plus artifact-owned code",
        "function references and direct calls",
        "call, recursion and native preflight suites",
    ),
];
