use super::templates::{borrowed, inline, traced};
use super::templates_scalar::mixed_scalar;
use super::templates_special::{affine_buffer, inert_value};
use super::MemoryObligation;

pub(super) const VALUES: &[MemoryObligation] = &[
    inline(
        "bool",
        "source through native",
        "bool",
        "tagged immediate bool",
        "constants and operations",
        "scalar differential suites",
    ),
    inert_value(
        "bytes",
        "immutable byte sequence",
        "static, stack, unique, region, sealed-shared-region, shared-node",
        "reserved source type parser path",
    ),
    borrowed(
        "byte-slice",
        "shared byte view",
        "immutable",
        "borrow expression and exact operation signatures",
        "ownership flow and boundary suites",
    ),
    borrowed(
        "byte-slice-mut",
        "exclusive byte view",
        "exclusive mutable",
        "borrow-mut expression and exact operation signatures",
        "ownership alias and mutation suites",
    ),
    affine_buffer(
        "byte-vector",
        "new-byte-vector and ownership lowering",
        "ownership and bulk-byte suites",
    ),
    traced(
        "buf",
        "transitional mutable byte buffer",
        "HeapObj::Buf(Vec<u8>)",
        "mutable",
        "none",
        "impossible",
        "observable buffer identity",
        "bounded variable bytes",
        "remove after byte-vector/bytes migration",
        "buffer operations, VM and native heap dispatch",
        "buffer boundary, host buffer, native allocation suites",
    ),
    inline(
        "capability",
        "source through VM",
        "typed provider capability",
        "tagged immediate capability token",
        "main grants and explicit parameters",
        "capability confinement and malformed bytecode suites",
    ),
    mixed_scalar(
        "f64",
        "native/evaluator bits; VM immediate NaN payload or HeapObj::Float",
        "constants and numeric operations",
        "numeric differential and conversion suites",
    ),
    mixed_scalar(
        "i64",
        "native/evaluator i64; VM tagged small integer or HeapObj::Int",
        "constants and numeric operations",
        "complete range and native scalar suites",
    ),
    traced(
        "path",
        "opaque immutable path bytes",
        "HeapObj::Path(Vec<u8>)",
        "immutable",
        "none",
        "impossible",
        "not source-observable",
        "bounded variable bytes",
        "static, unique, owned region, sealed-shared-region",
        "path constructors and host results",
        "opaque path and host capability suites",
    ),
    traced(
        "string",
        "immutable text value",
        "HeapObj::Str(String)",
        "immutable",
        "none",
        "impossible",
        "not source-observable",
        "bounded variable UTF-8 bytes",
        "static, stack, unique, region, sealed-shared-region, eligible shared-node",
        "literals, conversions, host results",
        "string, UTF-8, evaluator/VM/native suites",
    ),
    traced(
        "symbol",
        "immutable symbol value",
        "HeapObj::Symbol(String)",
        "immutable",
        "none",
        "impossible",
        "not source-observable",
        "bounded variable bytes",
        "static intern table or artifact-owned storage",
        "constants and runtime metadata",
        "constant and malformed bytecode suites",
    ),
    inline(
        "unit",
        "source through native",
        "unit",
        "tagged immediate unit",
        "constants and structured control",
        "scalar and structured outcome suites",
    ),
];
