use super::templates::inline;
use super::MemoryObligation;

pub(super) const STRUCTURAL: &[MemoryObligation] = &[
    inline(
        "builtin",
        "bytecode validation and operation registry",
        "validated operation identity",
        "validated bytecode operation ID; no runtime allocation",
        "bytecode operation dispatch; no runtime allocator",
        "operation registry and bytecode validation suites",
    ),
    inline(
        "closure",
        "source, HIR, SSA, bytecode, VM",
        "capture-free function value; captured closure graphs unsupported",
        "Value::Function with validated prototype ID",
        "validated zero-capture function references and calls",
        "closure call, validation, recursion and tail-call suites",
    ),
    structural_enum(
        "enum",
        "nominal immutable algebraic value",
        "enum constructors in evaluator, VM and native",
        "enum differential and malformed layout suites",
    ),
    structural_enum(
        "error",
        "typed immutable error enum",
        "numeric and host result constructors",
        "typed numeric, UTF-8 and system result suites",
    ),
    segmented_list(),
    structural_enum(
        "option",
        "generic immutable enum",
        "generic enum constructor",
        "Option evaluator/VM/native and malformed suites",
    ),
    MemoryObligation {
        identity: "product",
        authority: "verified HIR memory plan, SSA, bytecode, VM, native",
        semantic_type: "nominal immutable product",
        runtime_layout: "flat structural image or typed invocation-region record",
        value_semantics: "value",
        mutability: "immutable update publishes a new value",
        possible_aliases: "verified copy roots or invocation-local region handles",
        copyability: "mode-specific verified copy",
        current_ownership: "structural session or invocation region",
        escape_behavior: "key-free structural snapshot; region products cannot escape",
        lifetime: "session root release or invocation bulk reset",
        strong_cycles: "rejected",
        weak_links: "none",
        destructor: "iterative structural release or region bulk reset",
        external_resources: "prohibited",
        portability: "structural snapshots are send; region keys are worker-local",
        contention: "single-owner",
        allocation_frequency: "construction dependent",
        size_class: "bounded fields and structural image",
        current_trace_fields: "none",
        current_exact_roots: "none",
        object_identity: "none",
        current_placement: "structural root table or invocation region",
        candidate_placements: "current placement only until measured alternatives",
        reclamation_plan: "already deterministic",
        producers: "product construction in evaluator, VM and native",
        tests: "structural and region product differential suites",
        status: "current deterministic storage; unsupported closures reject",
    },
    structural_enum(
        "result",
        "generic immutable enum",
        "generic enum and host result constructors",
        "Result evaluator/VM/native and host suites",
    ),
    inline(
        "static-function",
        "HIR and SSA direct function identity",
        "static function",
        "FunctionId plus artifact-owned code",
        "function references and direct calls",
        "call, recursion and native preflight suites",
    ),
];

const fn structural_enum(
    identity: &'static str,
    semantic_type: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "verified HIR memory plan, SSA, bytecode, evaluator, VM and native",
        semantic_type,
        runtime_layout: "bounded flat structural image",
        value_semantics: "immutable value",
        mutability: "immutable",
        possible_aliases: "verified structural value copies",
        copyability: "mode-specific verified structural copy",
        current_ownership: "structural session root table",
        escape_behavior: "key-free structural snapshot",
        lifetime: "structural root release",
        strong_cycles: "rejected unless represented by a regular finite structural plan",
        weak_links: "none",
        destructor: "iterative structural release",
        external_resources: "prohibited",
        portability: "owned snapshots are send",
        contention: "single-owner",
        allocation_frequency: "construction dependent",
        size_class: "bounded variants, fields and image nodes",
        current_trace_fields: "none",
        current_exact_roots: "none",
        object_identity: "none",
        current_placement: "structural root table",
        candidate_placements: "current placement only until measured alternatives",
        reclamation_plan: "deterministic structural release",
        producers,
        tests,
        status: "current deterministic storage; unsupported shapes reject",
    }
}

const fn segmented_list() -> MemoryObligation {
    MemoryObligation {
        identity: "list",
        authority: "source, HIR witness, SSA, evaluator, VM, native",
        semantic_type: "persistent immutable list",
        runtime_layout: "inline empty or typed segmented session-region handle",
        value_semantics: "immutable value",
        mutability: "append-only private arena; published entries immutable",
        possible_aliases: "copied region handles and retained tails",
        copyability: "region-handle copy for selected elements",
        current_ownership: "invocation ordinary region",
        escape_behavior: "key-free flat owned-list snapshot",
        lifetime: "invocation region or returned snapshot owner",
        strong_cycles: "impossible for validated tail edges",
        weak_links: "none",
        destructor: "bulk session-region reset",
        external_resources: "prohibited",
        portability: "worker-local runtime; process-safe snapshot",
        contention: "single invocation owner",
        allocation_frequency: "one physical segment per bounded entry block",
        size_class: "capacity-32 segments",
        current_trace_fields: "none for list liveness",
        current_exact_roots: "compatibility legacy elements only",
        object_identity: "none",
        current_placement: "SegmentedListArena",
        candidate_placements: "sealed segment domains for immutable structural elements",
        reclamation_plan: "bulk region reset without reachability traversal",
        producers: "list constructors and generated runtime services",
        tests: "all-engine list equality, limits, branching and snapshot suites",
        status: "current selected copy-leaf region; other witnesses fail closed",
    }
}
