use super::templates::host_owned;
use super::MemoryObligation;

pub(super) const ARTIFACTS: &[MemoryObligation] = &[
    host_owned(
        "bytecode-constants",
        "validated bytecode",
        "bounded typed constant Vec",
        "bytecode chunk owner",
        "reference bytecode lowering",
        "bytecode validation suites",
    ),
    host_owned(
        "diagnostics",
        "compiler and semantic workspace",
        "structured diagnostic records",
        "workspace snapshot or compiler error owner",
        "parser, analyzer and workspace transaction",
        "diagnostic and workspace transaction suites",
    ),
    host_owned(
        "hir",
        "compiler",
        "resolved typed HIR Rust graph",
        "compiler phase owner",
        "source analysis",
        "HIR behavior and ownership suites",
    ),
    host_owned(
        "module-graph",
        "package compiler",
        "validated module dependency graph",
        "package compilation",
        "module loading and resolution",
        "module/package conformance suites",
    ),
    host_owned(
        "package-metadata",
        "package authority",
        "canonical manifest, lock and interface records",
        "artifact or compilation",
        "package codec and content addressing",
        "package lock/check and contract suites",
    ),
    host_owned(
        "workspace-snapshot",
        "semantic workspace",
        "immutable typed program snapshot and revision facts",
        "workspace Arc revision owner",
        "typed semantic transaction",
        "snapshot, transaction and stale revision suites",
    ),
    host_owned(
        "source-tree",
        "compiler source authority",
        "transient validated modules and source text",
        "workspace import",
        "trusted source loader",
        "source closure, package and parser suites",
    ),
    host_owned(
        "ssa",
        "compiler and IR verifier",
        "typed SSA CFG and metadata",
        "VerifiedProgram owner",
        "SSA construction and independent verification",
        "SSA verification, normalization and differential suites",
    ),
    host_owned(
        "typed-hole-constructors",
        "semantic workspace",
        "checked legal constructor records",
        "one revision-labelled query page",
        "hole context and constructor checker",
        "typed-hole validity, query and transaction suites",
    ),
];
