use super::templates_runtime::runtime_state;
use super::MemoryObligation;

pub(super) const RUNTIME: &[MemoryObligation] = &[
    runtime_state(
        "cache-object",
        "JIT code/metadata cache owned records",
        "immutable code object references",
        "JitSession",
        "none for liveness",
        "frame metadata roots are separate",
        "artifact identity",
        "bounded session cache",
        "explicit cache owner and artifact lifetime",
        "drop cache object at session/invalidation boundary",
        "JIT compilation and installation",
        "code-cache accounting, W^X and repeated installation suites",
    ),
    runtime_state(
        "evaluator-state",
        "recursive EvalValue plus Rc<RefCell<Vec<u8>>> buffers",
        "buffer Rc aliases only",
        "one evaluation",
        "no tracing collector; cumulative accounting",
        "not applicable",
        "buffer identity only",
        "Rust-owned evaluator graph",
        "abstract unique, borrow, region, share and pool semantics",
        "deterministic abstract owner cleanup",
        "independent SSA evaluator",
        "evaluator/VM differential and ownership budget suites",
    ),
    runtime_state(
        "gc-heap",
        "GcHeap sparse stable-index table and layout tags",
        "Value handles alias slots",
        "VM or JIT session",
        "HeapObj::trace from exact roots",
        "VM stack/globals or native maps",
        "stable slot index",
        "process-local non-moving mark/sweep heap",
        "typed unique, region, shared-region, shared-node, pool and static domains",
        "delete after all object families migrate",
        "VM and JIT session construction",
        "core collection, VM root and forced native collection suites",
    ),
    runtime_state(
        "native-frame",
        "registered generated frame plus exact stack-map homes",
        "active frame chain",
        "generated call",
        "typed live reference homes",
        "materialized roots across all active frames",
        "frame identity",
        "native stack plus sys chain",
        "typed owners, borrows, regions, release and resource cleanup metadata",
        "unregister on every structured outcome",
        "native encoder and sys executable state",
        "native roots, active frames, outcomes and image integrity suites",
    ),
    runtime_state(
        "resource-table",
        "typed host resource entries indexed by monotonic tokens",
        "one affine owner plus borrowed standard input",
        "VM session or explicit close",
        "none",
        "none",
        "external resource identity",
        "VM-owned resource table",
        "typed generational slots",
        "exact close/drop then slot generation invalidation",
        "VM host providers",
        "resource kind, close, stale token and host operation suites",
    ),
    runtime_state(
        "returned-value",
        "OwnedValue plus sparse traced heap snapshot",
        "reachable handles in snapshot",
        "host wrapper",
        "reachable HeapObj edges",
        "one result root during snapshot",
        "source value identity only",
        "owned return wrapper",
        "unique graph, region owner, sealed region, eligible shared roots, pool owner, static",
        "drop explicit returned owner",
        "VM into_owned and JIT snapshot",
        "returned heap ownership and cross-engine result suites",
    ),
    runtime_state(
        "vm-frame",
        "stack range plus frame metadata",
        "values alias GcHeap stable handles",
        "bytecode call",
        "all operand/local values through shared VM stack",
        "VM stack and globals",
        "frame identity not observable",
        "VM stack",
        "typed inline and owner slots with cleanup blocks",
        "pop exact owners and cleanup obligations",
        "validated bytecode dispatch",
        "tail-call, frame limit, root and structured outcome suites",
    ),
];
