use super::templates_special::target;
use super::MemoryObligation;

pub(super) const TARGETS: &[MemoryObligation] = &[
    target(
        "compiler-phase",
        "parse, HIR, SSA or normalization phase owner",
        "owned phase graph",
        "phase-private mutable then immutable",
        "internal cycles allowed",
        "value identities",
        "ordinary region and sealed interface region",
        "bulk region destruction",
        "compiler pipeline",
        "compiler request retention and phase reset evidence required",
    ),
    target(
        "component-storage",
        "typed ECS component collection",
        "mutable identity storage",
        "exclusive/disjoint mutable access",
        "cycles by IDs",
        "pool identity",
        "typed generational pool pages",
        "slot removal or pool destruction",
        "game ECS",
        "component insertion/removal and disjoint access evidence required",
    ),
    target(
        "cyclic-graph",
        "mutable or immutable cyclic graph",
        "owner-defined graph",
        "region-private or pool mutation",
        "internal cycles allowed",
        "pool or region identity",
        "ordinary region, sealed internal graph, typed pool IDs",
        "bulk owner destruction",
        "graph workload",
        "region graph, pool graph and weak backlink evidence required",
    ),
    target(
        "database-page",
        "mutable database page",
        "mutable identity",
        "exclusive transaction mutation",
        "cycles and backlinks by IDs",
        "pool identity",
        "typed page pool and transaction region",
        "slot removal, pool destruction, transaction rollback",
        "database workload",
        "stale page ID, rollback and page pool evidence required",
    ),
    target(
        "game-entity",
        "entity identity",
        "mutable identity",
        "pool-mediated mutation",
        "cycles by IDs",
        "pool identity",
        "ECS generational pool",
        "despawn or world destruction",
        "game ECS",
        "spawn, despawn, generation and frame jitter evidence required",
    ),
    target(
        "ordinary-region",
        "affine owned allocation domain",
        "region-owned values",
        "owner window",
        "internal cycles allowed",
        "region-relative value identity",
        "bounded region chunks",
        "exact side drops and bulk chunk free",
        "compiler region inference",
        "split, reset, outcome cleanup and size exhaustion evidence required",
    ),
    target(
        "pool",
        "typed mutable identity owner",
        "pool-owned identity",
        "exclusive/disjoint mutation",
        "cycles by IDs",
        "pool identity",
        "typed pages, generations and dense storage",
        "slot removal or bulk pool destruction",
        "pool operations",
        "stale ID, generation exhaustion, movement and cycle evidence required",
    ),
    target(
        "pool-id",
        "typed non-owning generational ID",
        "non-owning ID",
        "immutable",
        "cycles do not own storage",
        "pool identity",
        "inline index, generation and pool identity",
        "none; checked target pool owns storage",
        "pool operations",
        "stale rejection and generation wrap evidence required",
    ),
    target(
        "precise-shared-node",
        "eligible immutable acyclic shared value",
        "immutable value",
        "immutable",
        "strong graph acyclic by publication",
        "explicit shared identity only if semantic",
        "worker-local precise count after borrow/region/copy rejection",
        "bounded iterative release",
        "sharing analysis",
        "no-RC counterexample and retain/release balance evidence required",
    ),
    target(
        "sealed-shared-region",
        "immutable ownership capsule",
        "immutable graph",
        "sealed immutable",
        "internal cycles allowed; dependency graph acyclic",
        "region identity",
        "sealed shared region with one owner count",
        "release ledger then free chunks without tracing",
        "region sealing analysis",
        "seal, dependency DAG, cycle rejection and retention evidence required",
    ),
    target(
        "weak-reference",
        "checked non-owning link",
        "non-owning link",
        "immutable reference state",
        "never a strong ownership edge",
        "target class and generation",
        "weak handle or pool ID",
        "none; upgrade checks owner state",
        "weak-link construction",
        "upgrade and stale failure evidence required",
    ),
    target(
        "web-request",
        "request ownership scope",
        "request-owned graph",
        "request-private mutable",
        "internal region cycles allowed",
        "connection external identity",
        "request region plus affine connection and shared sealed router",
        "all-outcome request cleanup",
        "Web runtime",
        "timeout, cancellation, borrowed body and response evidence required",
    ),
];
