/// One deterministic inventory record. It is derived evidence, not semantic authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MemoryObligation {
    pub identity: &'static str,
    pub authority: &'static str,
    pub semantic_type: &'static str,
    pub runtime_layout: &'static str,
    pub value_semantics: &'static str,
    pub mutability: &'static str,
    pub possible_aliases: &'static str,
    pub copyability: &'static str,
    pub current_ownership: &'static str,
    pub escape_behavior: &'static str,
    pub lifetime: &'static str,
    pub strong_cycles: &'static str,
    pub weak_links: &'static str,
    pub destructor: &'static str,
    pub external_resources: &'static str,
    pub portability: &'static str,
    pub contention: &'static str,
    pub allocation_frequency: &'static str,
    pub size_class: &'static str,
    pub current_trace_fields: &'static str,
    pub current_exact_roots: &'static str,
    pub object_identity: &'static str,
    pub current_placement: &'static str,
    pub candidate_placements: &'static str,
    pub reclamation_plan: &'static str,
    pub producers: &'static str,
    pub tests: &'static str,
    pub status: &'static str,
}
