use super::MemoryObligation;

pub const fn resource(
    identity: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "source, HIR, SSA, bytecode, VM resource table",
        semantic_type: identity,
        runtime_layout: "immediate typed resource token plus ResourceTable entry",
        value_semantics: "external identity",
        mutability: "provider-defined",
        possible_aliases: "borrowed parameter or one affine owner",
        copyability: "not copyable",
        current_ownership: "affine direct value",
        escape_behavior: "move, return from helper, explicit close/drop",
        lifetime: "owner scope; complete implicit cleanup not Current",
        strong_cycles: "prohibited",
        weak_links: "none",
        destructor: "explicit typed close/drop; RAII teardown is safety cleanup",
        external_resources: "contains exact provider resource",
        portability: "worker-local",
        contention: "single-owner",
        allocation_frequency: "acquisition dependent",
        size_class: "immediate token plus host slot",
        current_trace_fields: "none",
        current_exact_roots: "none; resource obligation is separate",
        object_identity: "external identity",
        current_placement: "monotonic typed resource table slot",
        candidate_placements: "typed generational external slot",
        reclamation_plan: "compiler-inserted exactly-once close on every outcome",
        producers,
        tests,
        status: "accepted contract; explicit affine foundation Current",
    }
}

pub const fn affine_buffer(
    identity: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "source, HIR, SSA, evaluator, validated bytecode, VM",
        semantic_type: "exact affine byte-vector",
        runtime_layout: "execution-owned UniqueStore ByteVectorKey",
        value_semantics: "unique owned value",
        mutability: "exclusive borrow only",
        possible_aliases: "verified temporary loans",
        copyability: "affine",
        current_ownership: "whole-place unique owner through evaluator, VM, and forced native",
        escape_behavior: "explicit move or return",
        lifetime: "owner and inferred same-block loans",
        strong_cycles: "impossible",
        weak_links: "none",
        destructor: "explicit verified Drop followed by PlaceEnd",
        external_resources: "none",
        portability: "worker-local Current",
        contention: "single-owner",
        allocation_frequency: "operation dependent",
        size_class: "bounded variable bytes",
        current_trace_fields: "none",
        current_exact_roots: "none in evaluator/VM; native is fail-closed",
        object_identity: "runtime-local generation-bearing owner key",
        current_placement: "execution-owned unique store in evaluator, VM, and forced native",
        candidate_placements: "stack header plus unique allocation or owned region",
        reclamation_plan: "exact owner drop after final loan",
        producers,
        tests,
        status: "current exact evaluator/VM/forced-native byte-vector subset",
    }
}

pub const fn immutable_bytes() -> MemoryObligation {
    MemoryObligation {
        identity: "bytes",
        authority: "source, HIR, SSA, evaluator, validated bytecode, VM",
        semantic_type: "exact immutable bytes",
        runtime_layout: "static constant or execution-owned UniqueStore BytesKey",
        value_semantics: "copyable static value or affine dynamic value",
        mutability: "immutable",
        possible_aliases: "static sharing or explicit dynamic borrow",
        copyability: "static direct; dynamic only through clone-bytes or copy-bytes-slice",
        current_ownership: "static constant or one dynamic owner key",
        escape_behavior: "owned return snapshot; loans cannot escape",
        lifetime: "static program storage or exact owner drop",
        strong_cycles: "impossible",
        weak_links: "none",
        destructor: "dynamic exact Bytes drop glue",
        external_resources: "prohibited",
        portability: "evaluator/VM portable; native unsupported",
        contention: "single dynamic owner",
        allocation_frequency: "clone, slice copy, or static thaw",
        size_class: "bounded constant or retained unique bytes",
        current_trace_fields: "none",
        current_exact_roots: "none in evaluator/VM; native fail-closed",
        object_identity: "none",
        current_placement: "static bytecode data or evaluator/VM unique store",
        candidate_placements: "owned region after native unique lowering",
        reclamation_plan: "exact owner drop after final loan",
        producers: "bytes-literal, clone, slice copy, freeze",
        tests: "literal, ownership, evaluator/VM, allocation and forced-tier rejection suites",
        status: "current exact evaluator/VM family; native fail-closed",
    }
}

#[allow(clippy::too_many_arguments)]
pub const fn target(
    identity: &'static str,
    semantic_type: &'static str,
    semantics: &'static str,
    mutability: &'static str,
    cycles: &'static str,
    identity_kind: &'static str,
    candidates: &'static str,
    reclamation: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "representative workload target",
        semantic_type,
        runtime_layout: "not Current",
        value_semantics: semantics,
        mutability,
        possible_aliases: "defined by selected region, pool, borrow, or share plan",
        copyability: "not inferred Current",
        current_ownership: "not Current",
        escape_behavior: "workload boundary Target",
        lifetime: "owner boundary Target",
        strong_cycles: cycles,
        weak_links: "checked weak or generational ID where selected",
        destructor: "exact owner cleanup Target",
        external_resources: "only through exact side-drop contract",
        portability: "derived Target",
        contention: "single-owner by default",
        allocation_frequency: "workload dependent",
        size_class: "workload dependent",
        current_trace_fields: "none; workload is not Current",
        current_exact_roots: "none",
        object_identity: identity_kind,
        current_placement: "not Current",
        candidate_placements: candidates,
        reclamation_plan: reclamation,
        producers,
        tests,
        status: "accepted target; implementation evidence required",
    }
}
