use super::MemoryObligation;

pub const fn resource(
    identity: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "source, HIR, SSA, bytecode, VM resource table",
        semantic_type: identity,
        runtime_layout: "immediate typed resource token plus ResourceTable entry",
        value_semantics: "external identity",
        mutability: "provider-defined",
        possible_aliases: "borrowed parameter or one affine owner",
        copyability: "not copyable",
        current_ownership: "affine direct value",
        escape_behavior: "move, return from helper, explicit close/drop",
        lifetime: "owner scope; complete implicit cleanup not Current",
        strong_cycles: "prohibited",
        weak_links: "none",
        destructor: "explicit typed close/drop; RAII teardown is safety cleanup",
        external_resources: "contains exact provider resource",
        portability: "worker-local",
        contention: "single-owner",
        allocation_frequency: "acquisition dependent",
        size_class: "immediate token plus host slot",
        current_trace_fields: "none",
        current_exact_roots: "none; resource obligation is separate",
        object_identity: "external identity",
        current_placement: "monotonic typed resource table slot",
        candidate_placements: "typed generational external slot",
        reclamation_plan: "compiler-inserted exactly-once close on every outcome",
        producers,
        tests,
        status: "accepted contract; explicit affine foundation Current",
    }
}

pub const fn affine_buffer(
    identity: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "source, HIR, SSA; VM storage is transitional",
        semantic_type: "owned byte buffer",
        runtime_layout: "Owned Buf in IR; GcHeap Buf after bytecode erasure",
        value_semantics: "unique owned value",
        mutability: "exclusive borrow only",
        possible_aliases: "verified temporary loans",
        copyability: "affine",
        current_ownership: "whole-place unique owner in compiler",
        escape_behavior: "explicit move or return",
        lifetime: "owner and inferred same-block loans",
        strong_cycles: "impossible",
        weak_links: "none",
        destructor: "PlaceEnd fact; deterministic runtime free not Current",
        external_resources: "none",
        portability: "worker-local Current",
        contention: "single-owner",
        allocation_frequency: "operation dependent",
        size_class: "bounded variable bytes",
        current_trace_fields: "none; underlying Buf is a traced leaf",
        current_exact_roots: "underlying handle in VM/native maps",
        object_identity: "transitional Buf identity only",
        current_placement: "compiler affine fact over traced Buf storage",
        candidate_placements: "stack header plus unique allocation or owned region",
        reclamation_plan: "exact owner drop after final loan",
        producers,
        tests,
        status: "current compiler island; deterministic storage accepted",
    }
}

pub const fn inert_value(
    identity: &'static str,
    semantic_type: &'static str,
    candidates: &'static str,
    producers: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "accepted source contract",
        semantic_type,
        runtime_layout: "PLACEHOLDER: rejected before execution",
        value_semantics: "immutable value Target",
        mutability: "immutable Target",
        possible_aliases: "not Current",
        copyability: "compiler-selected Target",
        current_ownership: "none",
        escape_behavior: "not Current",
        lifetime: "not Current",
        strong_cycles: "not applicable",
        weak_links: "none",
        destructor: "not Current",
        external_resources: "prohibited",
        portability: "not Current",
        contention: "not Current",
        allocation_frequency: "none Current",
        size_class: "not Current",
        current_trace_fields: "none",
        current_exact_roots: "none",
        object_identity: "none Target",
        current_placement: "PLACEHOLDER",
        candidate_placements: candidates,
        reclamation_plan: "selected deterministic owner Target",
        producers,
        tests: "parser rejection and PLACEHOLDER status tests",
        status: "PLACEHOLDER accepted contract",
    }
}

#[allow(clippy::too_many_arguments)]
pub const fn target(
    identity: &'static str,
    semantic_type: &'static str,
    semantics: &'static str,
    mutability: &'static str,
    cycles: &'static str,
    identity_kind: &'static str,
    candidates: &'static str,
    reclamation: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "representative workload target",
        semantic_type,
        runtime_layout: "not Current",
        value_semantics: semantics,
        mutability,
        possible_aliases: "defined by selected region, pool, borrow, or share plan",
        copyability: "not inferred Current",
        current_ownership: "not Current",
        escape_behavior: "workload boundary Target",
        lifetime: "owner boundary Target",
        strong_cycles: cycles,
        weak_links: "checked weak or generational ID where selected",
        destructor: "exact owner cleanup Target",
        external_resources: "only through exact side-drop contract",
        portability: "derived Target",
        contention: "single-owner by default",
        allocation_frequency: "workload dependent",
        size_class: "workload dependent",
        current_trace_fields: "none; workload is not Current",
        current_exact_roots: "none",
        object_identity: identity_kind,
        current_placement: "not Current",
        candidate_placements: candidates,
        reclamation_plan: reclamation,
        producers,
        tests,
        status: "accepted target; implementation evidence required",
    }
}
