use super::MemoryObligation;

pub const fn inline(
    identity: &'static str,
    authority: &'static str,
    semantic_type: &'static str,
    layout: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority,
        semantic_type,
        runtime_layout: layout,
        value_semantics: "value",
        mutability: "immutable",
        possible_aliases: "copies only",
        copyability: "bitwise copy",
        current_ownership: "copy",
        escape_behavior: "unrestricted value escape",
        lifetime: "containing value",
        strong_cycles: "impossible",
        weak_links: "none",
        destructor: "trivial",
        external_resources: "none",
        portability: "send",
        contention: "single-owner",
        allocation_frequency: "none",
        size_class: "inline word or register",
        current_trace_fields: "none",
        current_exact_roots: "none",
        object_identity: "none",
        current_placement: "inline",
        candidate_placements: "inline, stack, caller-destination, static",
        reclamation_plan: "none",
        producers,
        tests,
        status: "current",
    }
}

#[allow(clippy::too_many_arguments)]
pub const fn traced(
    identity: &'static str,
    semantic_type: &'static str,
    layout: &'static str,
    mutability: &'static str,
    trace_fields: &'static str,
    cycles: &'static str,
    object_identity: &'static str,
    size: &'static str,
    candidates: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "source, HIR, SSA, bytecode, VM, native",
        semantic_type,
        runtime_layout: layout,
        value_semantics: "value unless object identity says otherwise",
        mutability,
        possible_aliases: "stable-index handles may alias",
        copyability: "handle copy in Current runtime",
        current_ownership: "session tracing heap",
        escape_behavior: "stack, globals, closures, fields, result snapshot",
        lifetime: "collector reachability or returned snapshot",
        strong_cycles: cycles,
        weak_links: "none Current",
        destructor: "sweep drops Rust payload",
        external_resources: "prohibited",
        portability: "worker-local Current",
        contention: "single-owner",
        allocation_frequency: "allocation-site dependent",
        size_class: size,
        current_trace_fields: trace_fields,
        current_exact_roots: "VM stack/globals and exact native frame maps",
        object_identity,
        current_placement: "GcHeap stable-index object",
        candidate_placements: candidates,
        reclamation_plan: "migrate, then remove tracing; selected candidate owns cleanup",
        producers,
        tests,
        status: "current collector; accepted deterministic candidates",
    }
}

pub const fn borrowed(
    identity: &'static str,
    semantic_type: &'static str,
    mutability: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority: "source, HIR, SSA, evaluator, validated bytecode, VM",
        semantic_type,
        runtime_layout: "bounded UniqueStore owner/range/loan token",
        value_semantics: "non-owning view",
        mutability,
        possible_aliases: "verified loan rules",
        copyability: "shared only when loan permits",
        current_ownership: "borrow of affine byte-vector place",
        escape_behavior: "same-block direct argument or let only",
        lifetime: "compiler-inferred bounded lexical/NLL slice",
        strong_cycles: "impossible",
        weak_links: "not a weak reference",
        destructor: "end borrow",
        external_resources: "none",
        portability: "worker-local",
        contention: "single-owner",
        allocation_frequency: "one bounded runtime loan record",
        size_class: "view metadata Target",
        current_trace_fields: "none",
        current_exact_roots: "none in evaluator/VM; native is fail-closed",
        object_identity: "none",
        current_placement: "verified lexical loan retained by evaluator/VM",
        candidate_placements: "stack view or register range",
        reclamation_plan: "owner destruction after final loan",
        producers,
        tests,
        status: "current exact evaluator/VM family; native fail-closed",
    }
}

pub const fn host_owned(
    identity: &'static str,
    authority: &'static str,
    layout: &'static str,
    lifetime: &'static str,
    producers: &'static str,
    tests: &'static str,
) -> MemoryObligation {
    MemoryObligation {
        identity,
        authority,
        semantic_type: "host/compiler artifact",
        runtime_layout: layout,
        value_semantics: "owned host value",
        mutability: "phase-private or immutable after publication",
        possible_aliases: "Rust ownership or explicit shared owner",
        copyability: "type-specific clone only",
        current_ownership: "Rust RAII owner",
        escape_behavior: "explicit API return or cache owner",
        lifetime,
        strong_cycles: "not admitted by contract",
        weak_links: "type-specific",
        destructor: "Rust field drop",
        external_resources: "type-specific explicit owner",
        portability: "type-specific",
        contention: "single-owner by default",
        allocation_frequency: "workload dependent",
        size_class: "bounded aggregate",
        current_trace_fields: "none for liveness",
        current_exact_roots: "none",
        object_identity: "stable semantic identity, not allocation identity",
        current_placement: "Rust stack and owned heap containers",
        candidate_placements: "phase region, sealed shared region, static artifact",
        reclamation_plan: "owner or phase end",
        producers,
        tests,
        status: "current host ownership; region migration accepted",
    }
}
