//! Dense bytecode opcodes for the register/stack hybrid VM.

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Op {
    Nop = 0,
    LoadConst = 1,
    LoadLocal = 2,
    StoreLocal = 3,
    LoadGlobal = 4,
    StoreGlobal = 5,
    Add = 10,
    Sub = 11,
    Mul = 12,
    Div = 13,
    Eq = 20,
    Ne = 21,
    Lt = 22,
    Le = 23,
    Gt = 24,
    Ge = 25,
    Not = 26,
    BitAnd = 27,
    BitOr = 28,
    BitXor = 29,
    Jump = 30,
    JumpIfFalse = 31,
    Call = 40,
    Return = 41,
    MakeClosure = 42,
    Cons = 50,
    Car = 51,
    Cdr = 52,
    IsNull = 53,
    Print = 60,
    Flush = 61,
    ReadByte = 62,
    WriteByte = 63,
    Exit = 64,
    WriteStr = 65,
    BufNew = 66,
    BufLen = 67,
    BufRef = 68,
    BufSet = 69,
    BufGetU32 = 72,
    BufSetU32 = 73,
    SysTtyGet = 74,
    SysPoll = 75,
    StdinHandle = 76,
    SysIsatty = 77,
    SysTtyGuardSave = 78,
    SysTtyGuardClear = 79,
    SysTtySet = 83,
    BufClone = 85,
    StrLen = 90,
    StrRef = 91,
    StrAppend = 92,
    StrSlice = 93,
    StrFromByte = 94,
    SysOpenRead = 100,
    SysOpenWrite = 101,
    SysClose = 102,
    SysReadByte = 103,
    SysWriteByte = 104,
    Arg = 110,
    Argc = 111,
    EmptyStr = 112,
    SysNowMs = 123,
    SysWaitMs = 124,
    SysSocket = 130,
    SysBind = 131,
    SysListen = 132,
    SysAccept = 133,
    SysPathExists = 134,
    SysRecv = 135,
    SysSend = 136,
    OkWrap = 140,
    ErrWrap = 141,
    IsOk = 142,
    UnwrapOk = 143,
    UnwrapErr = 144,
    IsNil = 145,
    StrFromI64 = 146,
    StrFromF64 = 147,
    Pop = 70,
    Dup = 71,
    False = 80,
    True = 81,
    Nil = 82,
    Unit = 84,
}

impl Op {
    pub fn from_byte(byte: u8) -> Option<Self> {
        Some(match byte {
            0 => Self::Nop,
            1 => Self::LoadConst,
            2 => Self::LoadLocal,
            3 => Self::StoreLocal,
            4 => Self::LoadGlobal,
            5 => Self::StoreGlobal,
            10 => Self::Add,
            11 => Self::Sub,
            12 => Self::Mul,
            13 => Self::Div,
            20 => Self::Eq,
            21 => Self::Ne,
            22 => Self::Lt,
            23 => Self::Le,
            24 => Self::Gt,
            25 => Self::Ge,
            26 => Self::Not,
            27 => Self::BitAnd,
            28 => Self::BitOr,
            29 => Self::BitXor,
            30 => Self::Jump,
            31 => Self::JumpIfFalse,
            40 => Self::Call,
            41 => Self::Return,
            42 => Self::MakeClosure,
            50 => Self::Cons,
            51 => Self::Car,
            52 => Self::Cdr,
            53 => Self::IsNull,
            60 => Self::Print,
            61 => Self::Flush,
            62 => Self::ReadByte,
            63 => Self::WriteByte,
            64 => Self::Exit,
            65 => Self::WriteStr,
            66 => Self::BufNew,
            67 => Self::BufLen,
            68 => Self::BufRef,
            69 => Self::BufSet,
            70 => Self::Pop,
            71 => Self::Dup,
            72 => Self::BufGetU32,
            73 => Self::BufSetU32,
            74 => Self::SysTtyGet,
            75 => Self::SysPoll,
            76 => Self::StdinHandle,
            77 => Self::SysIsatty,
            78 => Self::SysTtyGuardSave,
            79 => Self::SysTtyGuardClear,
            80 => Self::False,
            81 => Self::True,
            82 => Self::Nil,
            83 => Self::SysTtySet,
            84 => Self::Unit,
            85 => Self::BufClone,
            90 => Self::StrLen,
            91 => Self::StrRef,
            92 => Self::StrAppend,
            93 => Self::StrSlice,
            94 => Self::StrFromByte,
            100 => Self::SysOpenRead,
            101 => Self::SysOpenWrite,
            102 => Self::SysClose,
            103 => Self::SysReadByte,
            104 => Self::SysWriteByte,
            110 => Self::Arg,
            111 => Self::Argc,
            112 => Self::EmptyStr,
            123 => Self::SysNowMs,
            124 => Self::SysWaitMs,
            130 => Self::SysSocket,
            131 => Self::SysBind,
            132 => Self::SysListen,
            133 => Self::SysAccept,
            134 => Self::SysPathExists,
            135 => Self::SysRecv,
            136 => Self::SysSend,
            140 => Self::OkWrap,
            141 => Self::ErrWrap,
            142 => Self::IsOk,
            143 => Self::UnwrapOk,
            144 => Self::UnwrapErr,
            145 => Self::IsNil,
            146 => Self::StrFromI64,
            147 => Self::StrFromF64,
            _ => return None,
        })
    }

    pub const fn operand_width(self) -> usize {
        match self {
            Self::LoadConst
            | Self::LoadGlobal
            | Self::StoreGlobal
            | Self::Jump
            | Self::JumpIfFalse
            | Self::MakeClosure => 2,
            Self::LoadLocal | Self::StoreLocal | Self::Call => 1,
            _ => 0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::Op;

    #[test]
    fn byte_decoder_and_operand_widths_are_truthful() {
        assert_eq!(Op::from_byte(Op::LoadConst as u8), Some(Op::LoadConst));
        assert_eq!(Op::LoadConst.operand_width(), 2);
        assert_eq!(Op::Call.operand_width(), 1);
        assert_eq!(Op::Return.operand_width(), 0);
        assert_eq!(Op::from_byte(255), None);
    }
}
