[package]
name = "lkjscript-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
lkjscript-core = { path = "../lkjscript-core" }
lkjscript-host = { path = "../lkjscript-host" }
lkjscript-sys = { path = "../lkjscript-sys" }

[lints]
workspace = true
