[package]
name = "lkjscript2026-xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "lkjscript2026-xtask"
path = "src/main.rs"

[dependencies]
lkjscript2026-compiler = { path = "../lkjscript2026-compiler" }
lkjscript2026-core = { path = "../lkjscript2026-core" }

[lints]
workspace = true
