use crate::operation::*;

impl Operation {
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL
            .iter()
            .copied()
            .find(|operation| operation.name() == name)
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::Add => "+",
            Self::Subtract => "-",
            Self::Multiply => "*",
            Self::Divide => "div",
            Self::EqualValue => "equal-value",
            Self::SameObject => "same-object",
            Self::ListEqual => "list-equal",
            Self::F64BitsEqual => "f64-bits-equal",
            Self::Less => "lt",
            Self::LessEqual => "lte",
            Self::Greater => "gt",
            Self::GreaterEqual => "gte",
            Self::Not => "not",
            Self::Cons => "cons",
            Self::Car => "car",
            Self::Cdr => "cdr",
            Self::IsEmptyList => "empty-list?",
            Self::Print => "print",
            Self::Flush => "flush",
            Self::ReadByte => "read-byte",
            Self::WriteByte => "write-byte",
            Self::Exit => "exit",
            Self::BitAnd => "bit-and",
            Self::BitOr => "bit-or",
            Self::BitXor => "bit-xor",
            Self::And => "and",
            Self::Or => "or",
            Self::WriteStr => "write-str",
            Self::EmptyStr => "empty-str",
            Self::ArgCount => "argc",
            Self::Arg => "arg",
            Self::BufNew => "buf-new",
            Self::BufLen => "buf-len",
            Self::BufRef => "buf-ref",
            Self::BufSet => "buf-set",
            Self::OwnedBufNew => "owned-buf-new",
            Self::OwnedBufLen => "owned-buf-len",
            Self::OwnedBufRef => "owned-buf-ref",
            Self::OwnedBufSet => "owned-buf-set",
            Self::BufClone => "buf-clone",
            Self::BufFromStr => "buf-from-str",
            Self::BufToStr => "buf-to-str",
            Self::BufSlice => "buf-slice",
            Self::BufGetU32 => "buf-get-u32",
            Self::BufSetU32 => "buf-set-u32",
            Self::StrLen => "str-len",
            Self::StrRef => "str-ref",
            Self::StrAppend => "str-append",
            Self::StrSlice => "str-slice",
            Self::StrFromByte => "str-from-byte",
            Self::StrFromI64 => "str-from-i64",
            Self::StrFromF64 => "str-from-f64",
            Self::StdinHandle => "stdin-handle",
            Self::SysIsatty => "sys-isatty",
            Self::SysClose => "sys-close",
            Self::SysReadByte => "sys-read-byte",
            Self::SysWriteByte => "sys-write-byte",
            Self::SysReadInto => "sys-read-into",
            Self::SysWriteFrom => "sys-write-from",
            Self::SysTtyGuardSave => "sys-tty-guard-save",
            Self::SysTtyGuardClear => "sys-tty-guard-clear",
            Self::SysOpenRead => "sys-open-read",
            Self::SysOpenWrite => "sys-open-write",
            Self::SysOpenAppend => "sys-open-append",
            Self::SysOpenCreateNew => "sys-open-create-new",
            Self::SysOpenDir => "sys-open-dir",
            Self::SysFsync => "sys-fsync",
            Self::SysTruncate => "sys-truncate",
            Self::SysRename => "sys-rename",
            Self::SysRandomFill => "sys-random-fill",
            Self::SysSha256 => "sys-sha256",
            Self::SysSqliteOpen => "sys-sqlite-open",
            Self::SysSqliteClose => "sys-sqlite-close",
            Self::SysSqliteBusyTimeout => "sys-sqlite-busy-timeout",
            Self::SysSqliteExec => "sys-sqlite-exec",
            Self::SysSqlitePrepare => "sys-sqlite-prepare",
            Self::SysSqliteFinalize => "sys-sqlite-finalize",
            Self::SysSqliteReset => "sys-sqlite-reset",
            Self::SysSqliteClearBindings => "sys-sqlite-clear-bindings",
            Self::SysSqliteBindNull => "sys-sqlite-bind-null",
            Self::SysSqliteBindI64 => "sys-sqlite-bind-i64",
            Self::SysSqliteBindF64 => "sys-sqlite-bind-f64",
            Self::SysSqliteBindText => "sys-sqlite-bind-text",
            Self::SysSqliteBindBytes => "sys-sqlite-bind-bytes",
            Self::SysSqliteStep => "sys-sqlite-step",
            Self::SysSqliteColumnCount => "sys-sqlite-column-count",
            Self::SysSqliteColumnType => "sys-sqlite-column-type",
            Self::SysSqliteColumnI64 => "sys-sqlite-column-i64",
            Self::SysSqliteColumnF64 => "sys-sqlite-column-f64",
            Self::SysSqliteColumnText => "sys-sqlite-column-text",
            Self::SysSqliteColumnBytes => "sys-sqlite-column-bytes",
            Self::SysSqliteChanges => "sys-sqlite-changes",
            Self::SysSqliteLastInsertRowid => "sys-sqlite-last-insert-rowid",
            Self::SysSqliteExtendedResultCode => "sys-sqlite-extended-result-code",
            Self::SysSqliteBackup => "sys-sqlite-backup",
            Self::SysPathExists => "sys-path-exists",
            Self::SysWaitMs => "sys-wait-ms",
            Self::SysNowMs => "sys-now-ms",
            Self::SysSocket => "sys-socket",
            Self::SysBind => "sys-bind",
            Self::SysListen => "sys-listen",
            Self::SysAccept => "sys-accept",
            Self::SysRecv => "sys-recv",
            Self::SysSend => "sys-send",
            Self::SysPoll => "sys-poll",
            Self::SysTtyGet => "sys-tty-get",
            Self::SysTtySet => "sys-tty-set",
            Self::Ok => "ok",
            Self::Err => "err",
            Self::IsOk => "is-ok",
            Self::UnwrapOk => "unwrap-ok",
            Self::UnwrapErr => "unwrap-err",
            Self::Some => "some",
            Self::IsSome => "is-some",
            Self::UnwrapSome => "unwrap-some",
        }
    }
}
