[package]
name = "lkjscript-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "lkjscript"
path = "src/main.rs"

[[bin]]
name = "lkjscript-resource-bench"
path = "src/runtime/benchmark.rs"

[[bin]]
name = "lkjscript-cell"
path = "src/runtime/process_cell/main.rs"

[[bin]]
name = "lkjscriptd"
path = "../lkjscript-runtime/src/bin/lkjscriptd.rs"

[dependencies]
lkjscript-contracts = { path = "../lkjscript-contracts" }
lkjscript-core = { path = "../lkjscript-core" }
lkjscript-compiler = { path = "../lkjscript-compiler" }
lkjscript-ir = { path = "../lkjscript-ir" }
lkjscript-host = { path = "../lkjscript-host" }
lkjscript-jit = { path = "../lkjscript-jit" }
lkjscript-resource = { path = "../lkjscript-resource" }
lkjscript-runtime = { path = "../lkjscript-runtime" }
lkjscript-sys = { path = "../lkjscript-sys" }
lkjscript-vm = { path = "../lkjscript-vm" }


[dev-dependencies]
lkjscript-native = { path = "../lkjscript-native" }

[lints]
workspace = true
