use crate::semantic::schema::SemanticNodeKind as Kind;

pub(super) fn marker(kind: Kind) -> Option<&'static str> {
    Some(match kind {
        Kind::Import => "import",
        Kind::Main => "main",
        Kind::FunctionDeclaration => "def",
        Kind::Function => "fn",
        Kind::Signature => "sig",
        Kind::Parameters => "params",
        Kind::TypeVariables => "forall",
        Kind::Bounds => "bounds",
        Kind::Bound => "bound",
        Kind::Product => "product",
        Kind::ProductField | Kind::ProductValueField | Kind::FieldAccess => "field",
        Kind::EnumDeclaration => "enum",
        Kind::ContextVariants => "variants",
        Kind::EnumVariant | Kind::ContextVariant => "variant",
        Kind::EnumVariantField | Kind::VariantValueField => "variant-field",
        Kind::MarkerTrait | Kind::ContextTrait => "trait",
        Kind::TraitImplementation => "impl",
        Kind::ContextName => "name",
        Kind::ContextType => "type",
        Kind::ContextFields => "fields",
        Kind::ContextFor => "for",
        Kind::Let => "let",
        Kind::Bind => "bind",
        Kind::Var => "var",
        Kind::Set => "set",
        Kind::If => "if",
        Kind::While => "while",
        Kind::Loop => "loop",
        Kind::Return => "return",
        Kind::Break => "break",
        Kind::Continue => "continue",
        Kind::Trap => "trap",
        Kind::Exit => "exit",
        Kind::Do => "do",
        Kind::Quote => "quote",
        Kind::ProductValue => "product-value",
        Kind::VariantValue => "variant-value",
        Kind::Match => "match",
        Kind::MatchArms => "arms",
        Kind::MatchArm => "arm",
        Kind::WildcardPattern => "wildcard",
        Kind::BindingPattern => "binding",
        Kind::BoolPattern => "bool-pattern",
        Kind::I64Pattern => "i64-pattern",
        Kind::VariantPattern => "variant-pattern",
        Kind::VariantFieldPattern => "variant-field-pattern",
        Kind::ProductPattern => "product-pattern",
        Kind::ProductFieldPattern => "product-field-pattern",
        Kind::WithField => "with-field",
        Kind::EmptyList => "empty-list",
        Kind::None => "none",
        Kind::HoleGoal => "goal",
        Kind::Move => "move",
        Kind::Borrow => "borrow",
        Kind::BorrowMut => "borrow-mut",
        _ => return None,
    })
}
