use crate::semantic::schema::SemanticNodeKind as Kind;

pub(super) fn marker(kind: Kind) -> Option<&'static str> {
    Some(match kind {
        Kind::Import => "import",
        Kind::Main => "main",
        Kind::FunctionDeclaration => "def",
        Kind::Function => "fn",
        Kind::Signature => "sig",
        Kind::Parameters => "params",
        Kind::TypeVariables => "forall",
        Kind::Bounds => "bounds",
        Kind::Bound => "bound",
        Kind::Product => "product",
        Kind::ProductField | Kind::ProductValueField | Kind::FieldAccess => "field",
        Kind::EnumDeclaration => "enum",
        Kind::ContextVariants => "variants",
        Kind::EnumVariant => "variant",
        Kind::EnumVariantField => "variant-field",
        Kind::MarkerTrait | Kind::ContextTrait => "trait",
        Kind::TraitImplementation => "impl",
        Kind::ContextName => "name",
        Kind::ContextType => "type",
        Kind::ContextFields => "fields",
        Kind::ContextFor => "for",
        Kind::Let => "let",
        Kind::Bind => "bind",
        Kind::Var => "var",
        Kind::Set => "set",
        Kind::If => "if",
        Kind::While => "while",
        Kind::Do => "do",
        Kind::Quote => "quote",
        Kind::ProductValue => "product-value",
        Kind::WithField => "with-field",
        Kind::EmptyList => "empty-list",
        Kind::None => "none",
        Kind::HoleGoal => "goal",
        Kind::Move => "move",
        Kind::Borrow => "borrow",
        Kind::BorrowMut => "borrow-mut",
        _ => return None,
    })
}
