use crate::{ContractFact, ContractItem, ContractItemKind};

pub(super) fn runtime_slots() -> ContractItem {
    let facts = [
        (
            "identity-i64",
            "IdentityI64",
            "(state,i64)->i64 pure test boundary",
        ),
        (
            "poll",
            "Poll",
            "(state)->deadline and fuel status noncollecting",
        ),
        (
            "enter-function",
            "EnterFunction",
            "(state,function)->status",
        ),
        (
            "standard-input",
            "StdinHandle",
            "(island-state,capability/stdio)->resource/input-stream",
        ),
        (
            "byte-vector-new",
            "ByteVectorNew",
            "(island-state,i64)->unique/byte-vector",
        ),
        (
            "byte-vector-move",
            "ByteVectorMove",
            "(island-state,unique/byte-vector)->unique/byte-vector",
        ),
        (
            "byte-vector-borrow-shared",
            "ByteVectorBorrowShared",
            "(island-state,unique/byte-vector)->loan/byte-slice",
        ),
        (
            "byte-vector-borrow-exclusive",
            "ByteVectorBorrowExclusive",
            "(island-state,unique/byte-vector)->loan/byte-slice-mut",
        ),
        (
            "byte-slice-length",
            "ByteSliceLength",
            "(island-state,loan/byte-slice)->i64",
        ),
        (
            "byte-slice-byte-at",
            "ByteSliceByteAt",
            "(island-state,loan/byte-slice,i64)->i64",
        ),
        (
            "byte-slice-read-u32-little-endian",
            "ByteSliceReadU32Le",
            "(island-state,loan/byte-slice,i64)->i64",
        ),
        (
            "byte-slice-mut-set-byte",
            "ByteSliceMutSetByte",
            "(island-state,loan/byte-slice-mut,i64,i64)->unit",
        ),
        (
            "byte-slice-mut-write-u32-little-endian",
            "ByteSliceMutWriteU32Le",
            "(island-state,loan/byte-slice-mut,i64,i64)->unit",
        ),
        (
            "byte-slice-end",
            "ByteSliceEnd",
            "(island-state,loan/byte-slice)->unit",
        ),
        (
            "byte-slice-mut-end",
            "ByteSliceMutEnd",
            "(island-state,loan/byte-slice-mut)->unit",
        ),
        (
            "byte-vector-drop",
            "ByteVectorDrop",
            "(island-state,unique/byte-vector)->unit",
        ),
        (
            "static-bytes-length",
            "StaticBytesLength",
            "(island-state,static/bytes)->i64",
        ),
        (
            "static-bytes-byte-at",
            "StaticBytesByteAt",
            "(island-state,static/bytes,i64)->i64",
        ),
        (
            "static-bytes-clone",
            "StaticBytesClone",
            "(island-state,static/bytes)->unique/bytes",
        ),
        (
            "static-bytes-copy-slice",
            "StaticBytesCopySlice",
            "(island-state,static/bytes,i64,i64)->unique/bytes",
        ),
        (
            "static-bytes-thaw",
            "StaticBytesThaw",
            "(island-state,static/bytes)->unique/byte-vector",
        ),
        (
            "bytes-move",
            "BytesMove",
            "(island-state,unique/bytes)->unique/bytes",
        ),
        (
            "bytes-borrow-shared",
            "BytesBorrowShared",
            "(island-state,unique/bytes)->loan/bytes",
        ),
        (
            "bytes-length",
            "BytesLength",
            "(island-state,loan/bytes)->i64",
        ),
        (
            "bytes-byte-at",
            "BytesByteAt",
            "(island-state,loan/bytes,i64)->i64",
        ),
        (
            "bytes-clone",
            "BytesClone",
            "(island-state,loan/bytes)->unique/bytes",
        ),
        (
            "bytes-copy-slice",
            "BytesCopySlice",
            "(island-state,loan/bytes,i64,i64)->unique/bytes",
        ),
        (
            "bytes-end-borrow",
            "BytesEndBorrow",
            "(island-state,loan/bytes)->unit",
        ),
        (
            "bytes-drop",
            "BytesDrop",
            "(island-state,unique/bytes)->unit",
        ),
        (
            "freeze-byte-vector",
            "FreezeByteVector",
            "(island-state,unique/byte-vector)->unique/bytes",
        ),
        (
            "thaw-bytes",
            "ThawBytes",
            "(island-state,unique/bytes)->unique/byte-vector",
        ),
        (
            "structural-dispatch",
            "StructuralDispatch",
            "(island-state,verified-structural-site,up-to-three-words)->typed-word",
        ),
        (
            "heap-dispatch",
            "HeapDispatch",
            "(state,operation,args)->status",
        ),
        ("reserve-frame", "ReserveFrame", "(state,slots)->status"),
        ("register-frame", "RegisterFrame", "(state,frame)->status"),
        (
            "unregister-frame",
            "UnregisterFrame",
            "(state,frame)->status",
        ),
    ];
    facts.into_iter().fold(
        ContractItem::new("slots", ContractItemKind::Operation).semantic_order(),
        |item, (id, name, value)| item.fact(ContractFact::required(id, name, value)),
    )
}
