[package]
name = "lkjscript-jit"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
lkjscript-core = { path = "../lkjscript-core" }
lkjscript-ir = { path = "../lkjscript-ir" }
lkjscript-native = { path = "../lkjscript-native" }
lkjscript-resource = { path = "../lkjscript-resource" }
lkjscript-sys = { path = "../lkjscript-sys" }

[lints]
workspace = true
