#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RemovedSpelling {
    pub old: &'static str,
    pub replacement: &'static str,
}

pub const REMOVED_SPELLINGS: &[RemovedSpelling] = &[
    removed("+", "add"),
    removed("-", "subtract"),
    removed("*", "multiply"),
    removed("div", "divide"),
    removed("same-object", "is-same-object"),
    removed("list-equal", "equal-list"),
    removed("f64-bits-equal", "equal-f64-bits"),
    removed("f64-from-i64-exact", "convert-i64-to-f64-exact"),
    removed("f64-from-i64-rounded", "convert-i64-to-f64-rounded"),
    removed("i64-from-f64-exact", "convert-f64-to-i64-exact"),
    removed("i64-from-f64-trunc", "convert-f64-to-i64-truncating"),
    removed("lt", "less-than"),
    removed("lte", "less-than-or-equal"),
    removed("gt", "greater-than"),
    removed("gte", "greater-than-or-equal"),
    removed("cons", "list-prepend"),
    removed("car", "list-first"),
    removed("cdr", "list-rest"),
    removed("empty-list?", "is-empty-list"),
    removed("write-str", "write-string"),
    removed("empty-str", "empty-string"),
    removed("argc", "argument-count"),
    removed("arg", "argument-at"),
    removed("buf-len", "buf-length"),
    removed("buf-ref", "buf-byte-at"),
    removed("buf-set", "buf-set-byte"),
    removed("owned-buf-len", "byte-slice-length"),
    removed("owned-buf-ref", "byte-slice-byte-at"),
    removed("owned-buf-set", "byte-slice-mut-set-byte"),
    removed("owned-buf-new", "new-byte-vector"),
    removed("owned-buf-length", "byte-slice-length"),
    removed("owned-buf-byte-at", "byte-slice-byte-at"),
    removed("owned-buf-set-byte", "byte-slice-mut-set-byte"),
    removed("buf-clone", "copy-buf"),
    removed("buf-from-str", "convert-string-to-buf"),
    removed("buf-to-str", "convert-buf-to-string"),
    removed("path-from-str", "convert-string-to-path"),
    removed("path-from-buf", "convert-buf-to-path"),
    removed("path-to-buf", "convert-path-to-buf"),
    removed("path-to-str", "convert-path-to-string"),
    removed("buf-slice", "copy-buf-slice"),
    removed("buf-get-u32", "buf-read-u32"),
    removed("buf-set-u32", "buf-write-u32"),
    removed("str-len", "string-byte-length"),
    removed("str-ref", "string-byte-at"),
    removed("str-append", "append-string"),
    removed("str-slice", "copy-string-byte-slice"),
    removed("str-from-byte", "convert-byte-to-string"),
    removed("str-from-i64", "format-i64"),
    removed("str-from-f64", "format-f64"),
    removed("stdin-handle", "standard-input"),
    removed("sys-isatty", "is-terminal"),
    removed("sys-read-byte", "read-resource-byte"),
    removed("sys-write-byte", "write-resource-byte"),
    removed("sys-read-into", "read-into"),
    removed("sys-write-from", "write-from"),
    removed("sys-tty-guard-save", "save-terminal-guard"),
    removed("sys-tty-guard-clear", "clear-terminal-guard"),
    removed("sys-open-read", "open-file-reader"),
    removed("sys-open-write", "open-file-writer"),
    removed("sys-open-append", "open-file-appender"),
    removed("sys-open-create-new", "create-file"),
    removed("sys-open-dir", "open-directory"),
    removed("sys-fsync", "sync-file"),
    removed("sys-truncate", "truncate-file"),
    removed("sys-rename", "rename-path"),
    removed("sys-random-fill", "fill-random"),
    removed("sys-sha256", "sha256"),
    removed("sys-sqlite-open", "open-sqlite"),
    removed("sys-sqlite-close", "close-sqlite"),
    removed("sys-sqlite-busy-timeout", "set-sqlite-busy-timeout"),
    removed("sys-sqlite-exec", "execute-sqlite"),
    removed("sys-sqlite-prepare", "prepare-sqlite"),
    removed("sys-sqlite-finalize", "finalize-sqlite-statement"),
    removed("sys-sqlite-reset", "reset-sqlite-statement"),
    removed("sys-sqlite-clear-bindings", "clear-sqlite-bindings"),
    removed("sys-sqlite-bind-null", "bind-sqlite-null"),
    removed("sys-sqlite-bind-i64", "bind-sqlite-i64"),
    removed("sys-sqlite-bind-f64", "bind-sqlite-f64"),
    removed("sys-sqlite-bind-text", "bind-sqlite-string"),
    removed("sys-sqlite-bind-bytes", "bind-sqlite-bytes"),
    removed("sys-sqlite-step", "step-sqlite"),
    removed("sys-sqlite-column-count", "sqlite-column-count"),
    removed("sys-sqlite-column-type", "sqlite-column-type"),
    removed("sys-sqlite-column-i64", "sqlite-column-i64"),
    removed("sys-sqlite-column-f64", "sqlite-column-f64"),
    removed("sys-sqlite-column-text", "sqlite-column-string"),
    removed("sys-sqlite-column-bytes", "sqlite-column-bytes"),
    removed("sys-sqlite-changes", "sqlite-change-count"),
    removed("sys-sqlite-last-insert-rowid", "sqlite-last-insert-rowid"),
    removed(
        "sys-sqlite-extended-result-code",
        "sqlite-extended-result-code",
    ),
    removed("sys-sqlite-backup", "backup-sqlite"),
    removed("sys-path-exists", "does-path-exist"),
    removed("sys-wait-ms", "wait-milliseconds"),
    removed("sys-now-ms", "current-time-milliseconds"),
    removed("sys-socket", "open-tcp-socket"),
    removed("sys-bind", "bind-tcp"),
    removed("sys-listen", "listen-tcp"),
    removed("sys-accept", "accept-tcp"),
    removed("sys-recv", "receive-string"),
    removed("sys-send", "send-string"),
    removed("sys-poll", "poll-streams"),
    removed("sys-tty-get", "get-terminal-state"),
    removed("sys-tty-set", "set-terminal-state"),
    removed("->", "structured sig inputs/output"),
    removed(
        "str",
        "string-literal source marker; borrowed str type is reserved",
    ),
    removed("handle", "an exact typed resource kind"),
    removed("owned", "byte-vector"),
    removed("ref", "byte-slice"),
    removed("ref-mut", "byte-slice-mut"),
    removed("Never", "never"),
    removed("Unit", "unit"),
    removed("Bool", "bool"),
    removed("I64", "i64"),
    removed("F64", "f64"),
    removed("Str", "string"),
    removed("Buf", "buf"),
    removed("Path", "path"),
    removed("Symbol", "symbol"),
    removed("Handle", "handle"),
    removed("Capability", "capability"),
    removed("Owned", "owned"),
    removed("Ref", "ref"),
    removed("RefMut", "ref-mut"),
    removed("Product", "product"),
    removed("List", "list"),
    removed("Option", "option"),
    removed("Result", "result"),
    removed("NumericError", "numeric-error"),
    removed("Utf8Error", "utf8-error"),
    removed("SystemError", "system-error"),
    removed("Arguments", "arguments"),
    removed("Clock", "clock"),
    removed("Entropy", "entropy"),
    removed("FileSystem", "file-system"),
    removed("Network", "network"),
    removed("Sqlite", "sqlite"),
    removed("Stdio", "stdio"),
    removed("Terminal", "terminal"),
    removed("Copy", "copy"),
    removed("Clone", "clone"),
    removed("Drop", "drop"),
    removed("Send", "send"),
    removed("Sync", "sync"),
    removed("Some", "some"),
    removed("None", "none"),
    removed("Ok", "ok"),
    removed("Err", "err"),
    removed("NonFinite", "non-finite"),
    removed("OutOfRange", "out-of-range"),
    removed("Fractional", "fractional"),
    removed("Inexact", "inexact"),
    removed("UnexpectedContinuation", "unexpected-continuation"),
    removed("InvalidLeadingByte", "invalid-leading-byte"),
    removed("MissingContinuation", "missing-continuation"),
    removed("OverlongEncoding", "overlong-encoding"),
    removed("Surrogate", "surrogate"),
    removed("Io", "io"),
    removed("Time", "time"),
    removed("Random", "random"),
    removed("Utf8", "utf8"),
    removed("Unsupported", "unsupported"),
];

const fn removed(old: &'static str, replacement: &'static str) -> RemovedSpelling {
    RemovedSpelling { old, replacement }
}

pub fn removed_spelling(old: &str) -> Option<&'static RemovedSpelling> {
    REMOVED_SPELLINGS.iter().find(|record| record.old == old)
}
