use super::*;

pub(super) fn action(kind: i64, value: i64) -> Value {
    json!({"kind":kind,"value":value})
}

// A finite operation-word model, independent of the language's consuming implementation.
// No semantic requests are generated by this host oracle; all authored inputs are literal files.
pub(super) fn exhaustive() -> Vec<Vec<Value>> {
    let alphabet = [
        action(0, 7),
        action(0, -3),
        action(1, 0),
        action(2, 0),
        action(3, 41),
        action(4, 0),
    ];
    let mut words = vec![vec![]];
    let mut frontier = vec![vec![]];
    for _ in 0..4 {
        let mut next = Vec::new();
        for prefix in frontier {
            for operation in &alphabet {
                let mut word = prefix.clone();
                word.push(operation.clone());
                next.push(word);
            }
        }
        words.extend(next.iter().cloned());
        frontier = next;
    }
    assert_eq!(words.len(), 1555);
    words
}

pub(super) fn expected(actions: &[Value]) -> Value {
    let mut values = Vec::new();
    let mut events = Vec::new();
    for action in actions {
        let kind = action["kind"].as_i64().unwrap();
        let input = action["value"].as_i64().unwrap();
        let observed = match kind {
            0 => {
                values.push(input);
                Some(input)
            }
            1 => values.pop(),
            2 => values.first().copied(),
            3 => values
                .first_mut()
                .map(|slot| std::mem::replace(slot, input)),
            _ => {
                assert_eq!(kind, 4, "model covers valid operations only");
                values.clear();
                None
            }
        };
        events.push(json!({"kind":kind,"present":observed.is_some(),"value":observed.unwrap_or(0),"length":values.len()}));
    }
    values.reverse();
    json!({"events":events,"remaining":values,"empty":0,"reused":37})
}

pub(super) fn burst(length: usize) -> Vec<Value> {
    let mut actions: Vec<_> = (0..length).map(|n| action(0, n as i64 - 17)).collect();
    actions.extend([action(2, 0), action(3, 101), action(2, 0)]);
    actions.extend((0..length).map(|_| action(1, 0)));
    actions
}

pub(super) fn snapshot(original: &Value, replacement: &Value) -> Value {
    json!({"before":original,"displaced":original,"after":replacement,"removed":replacement,"empty":0})
}
