use crate::model::Policy;

use super::LimitRecord;

pub(super) fn records(policy: &Policy) -> Vec<LimitRecord> {
    vec![
        super::record(
            "repository.graph.nodes",
            "implementation-safety-maximum",
            "canonical nodes",
            "one revision graph",
            "build",
            "meta/structure/policy.json",
            policy.limits.graph_nodes,
            false,
            None,
            "canonicalize complete repository graph",
            "GraphBuildError::nodes",
            "complete graph or no graph and identity",
            "graph node count",
            false,
            true,
        ),
        super::record(
            "repository.graph.edges",
            "implementation-safety-maximum",
            "canonical edges",
            "one revision graph",
            "build",
            "meta/structure/policy.json",
            policy.limits.graph_edges,
            false,
            None,
            "canonicalize complete repository graph",
            "GraphBuildError::edges",
            "complete endpoint-closed graph or no publication",
            "graph edge count",
            false,
            true,
        ),
        super::record(
            "repository.graph.work",
            "implementation-safety-maximum",
            "charged work units",
            "one revision graph",
            "build",
            "meta/structure/policy.json",
            policy.limits.graph_work,
            false,
            None,
            "extract repository records",
            "GraphBuildError::work",
            "cumulative charge; failure publishes nothing",
            "work_used",
            false,
            true,
        ),
        super::record(
            "repository.graph.retained-bytes",
            "implementation-safety-maximum",
            "charged bytes",
            "one revision graph",
            "build",
            "meta/structure/policy.json",
            policy.limits.graph_bytes,
            false,
            None,
            "retain repository graph fields",
            "GraphBuildError::retained-bytes",
            "canonical node and edge field bytes; failure publishes nothing",
            "bytes_used",
            false,
            true,
        ),
        super::record(
            "repository.query.work",
            "query-output-budget",
            "charged work units",
            "one query view",
            "query",
            "meta/structure/policy.json",
            policy.limits.query_work,
            true,
            None,
            "traverse complete repository graph",
            "completion work-budget",
            "bounded result exposes deterministic frontier",
            "completion work and frontier",
            false,
            true,
        ),
        super::record(
            "repository.query.output-bytes",
            "query-output-budget",
            "serialized bytes",
            "one query publication",
            "query",
            "meta/structure/policy.json",
            policy.limits.query_bytes,
            true,
            None,
            "serialize repository query",
            "typed output byte error",
            "oversized serialization publishes nothing",
            "exact encoded bytes",
            false,
            true,
        ),
    ]
}
