use super::LimitRecord;

pub(super) fn records() -> Vec<LimitRecord> {
    let values = lkjscript_core::StructuralValueRuntimeLimits::default();
    let domains = values.domains;
    let roots = values.roots;
    vec![
        super::record(
            "structural.image.local-node-id",
            "addressability-maximum",
            "nodes",
            "one structural image",
            "image",
            "crates/lkjscript-core/src/structural/image/model.rs",
            u64::from(u32::MAX),
            false,
            Some(u64::from(u32::MAX)),
            "encode local node reference",
            "StructuralValueError::ArithmeticOverflow",
            "non-reservable representation bound",
            "image node count",
            false,
            false,
        ),
        super::record(
            "structural.image.tree-nodes.default",
            "resource-profile-quota",
            "semantic nodes",
            "one structural publication",
            "publication",
            "crates/lkjscript-core/src/structural/value_runtime/limits.rs",
            u64::from(values.max_tree_nodes),
            true,
            Some(u64::from(
                lkjscript_core::STRUCTURAL_TREE_NODE_SAFETY_MAXIMUM,
            )),
            "validate and build flat structural image",
            "StructuralValueLimit::TreeNodes",
            "preflight before image allocation or publication",
            "clone_nodes and release_work",
            false,
            false,
        ),
        super::record(
            "structural.image.tree-depth",
            "implementation-safety-maximum",
            "levels",
            "one semantic visitor",
            "visitor",
            "crates/lkjscript-core/src/structural/value_runtime/limits.rs",
            u64::from(values.max_tree_depth),
            true,
            Some(u64::from(u16::MAX)),
            "iterative semantic validation",
            "StructuralValueLimit::TreeDepth",
            "preflight before publication",
            "validated depth",
            false,
            false,
        ),
        super::record(
            "structural.image.fields-per-node",
            "implementation-safety-maximum",
            "field cells",
            "one product or active enum node",
            "node",
            "crates/lkjscript-core/src/structural/value_runtime/limits.rs",
            u64::from(values.max_fields),
            true,
            Some(u64::from(u16::MAX)),
            "validate structural node fields",
            "StructuralValueLimit::Fields",
            "preflight before builder mutation",
            "field cell count",
            false,
            false,
        ),
        super::record(
            "structural.image.payload-bytes.default",
            "resource-profile-quota",
            "bytes",
            "one structural image",
            "publication",
            "crates/lkjscript-core/src/structural/value_runtime/limits.rs",
            values.max_payload_bytes,
            true,
            Some(u64::from(u32::MAX)),
            "reserve image payload",
            "StructuralValueLimit::PayloadBytes",
            "preflight and fallible reserve before publication",
            "payload_bytes_live and peak",
            false,
            false,
        ),
        super::record(
            "structural.runtime.live-domains.default",
            "resource-profile-quota",
            "live domains",
            "one structural invocation",
            "invocation",
            "crates/lkjscript-core/src/structural/limits.rs",
            u64::from(domains.max_domains),
            true,
            Some(u64::from(u32::MAX)),
            "allocate coarse ownership domain",
            "StructuralLimit::Domains",
            "reserve live slot; release or rollback exactly once",
            "live_domains and peak_live_domains",
            false,
            false,
        ),
        super::record(
            "structural.runtime.live-roots.default",
            "resource-profile-quota",
            "live roots",
            "one structural invocation",
            "invocation",
            "crates/lkjscript-core/src/structural/root_table/limits.rs",
            u64::from(roots.max_roots),
            true,
            Some(u64::from(u32::MAX)),
            "publish compact structural root",
            "StructuralRootTableLimit::Roots",
            "publish atomically or return the typed root",
            "live_roots and root_slots_reused",
            false,
            false,
        ),
        super::record(
            "structural.runtime.live-objects.default",
            "resource-profile-quota",
            "live objects",
            "one structural invocation",
            "invocation",
            "crates/lkjscript-core/src/structural/value_runtime/limits.rs",
            u64::from(values.max_objects),
            true,
            Some(u64::from(u32::MAX)),
            "insert structural object",
            "StructuralValueLimit::Objects",
            "rollback object and domain before root publication",
            "live_objects and peak_live_objects",
            false,
            false,
        ),
        super::record(
            "structural.runtime.release-work",
            "resource-profile-quota",
            "domain work items",
            "one domain release closure",
            "release",
            "crates/lkjscript-core/src/structural/limits.rs",
            u64::from(domains.max_release_work),
            true,
            Some(u64::from(u32::MAX)),
            "release external domain dependencies",
            "StructuralLimit::ReleaseWork",
            "preflight complete iterative release plan",
            "release_work and release_backlog",
            false,
            false,
        ),
    ]
}
