use super::*;

fn build_input() -> Value {
    json!({"product":"demo", "version":"1", "capabilities":"abc"})
}

const HEADER: &str = concat!(
    "<!-- Generated by `lkjscript capabilities --generate-docs docs/generated`. ",
    "Do not edit. demo 1 capabilities `abc`. -->\n\n"
);

#[test]
fn registry_pages_preserve_order_and_escape_only_observed_content() {
    for (target, title) in [
        (
            "function-definition",
            "Revision-pinned function definition projection",
        ),
        ("deployment", "Deployment descriptor schema"),
    ] {
        let actual = render(target, json!([build_input(), "```<x>&日本語\n"]))
            .expect("native registry guide");
        assert_eq!(
            actual,
            format!(
                "{HEADER}# {title}\n\nThe following compact records are the executable-owned current public capability.\n\n<pre>```&lt;x&gt;&amp;日本語\n</pre>\n"
            )
        );
    }
    let change = render(
        "change-grammar",
        json!([build_input(), ["first\n", "second\n", "third\n"]]),
    )
    .expect("ordered native grammar");
    assert!(change.starts_with(&format!("{HEADER}# Change request grammar\n\n")));
    assert!(change.contains("(record create Greeting (visibility public)"));
    assert!(change.ends_with("<pre>first\nsecond\nthird\n</pre>\n"));
}

#[test]
fn standard_page_escapes_dynamic_identities_and_preserves_interface_payload() {
    let actual = render(
        "builtin-standard",
        json!([build_input(), {
            "package":"pkg<&", "revision":"rev`\"", "records":"owner reference=```<tag>&\n"
        }]),
    )
    .expect("native standard guide");
    assert!(actual.starts_with(&format!("{HEADER}# Built-in standard package public interface\n\nPackage <code>pkg&lt;&amp;</code> at exact package revision <code>rev`&quot;</code>.\n\n")));
    assert!(actual.contains("Only the standalone wrapper owns `transaction-outcome`"));
    assert!(actual.ends_with("<pre>owner reference=```&lt;tag&gt;&amp;\n</pre>\n"));
}

fn owner(kind: &str, name: &str, parent: &str, reference: &str) -> Value {
    json!({"kind":kind, "name":name, "parent":parent, "reference":reference})
}

fn relay_input(owners: Vec<Value>) -> Value {
    json!([build_input(), {
        "name":"demo", "purpose":"<purpose>", "runner":"http",
        "deployment":true, "artifact":"guide.lkja"
    }, owners, [{"name":"custom<&", "maximum":123}, {"name":"other", "maximum":456}]])
}

fn relay_owners() -> Vec<Value> {
    vec![
        owner("interface", "HttpClient", "", "client<&"),
        owner("operation", "get", "client<&", "client-get"),
        owner("operation", "get", "data", "not-the-client"),
    ]
}

#[test]
fn relay_selection_belongs_to_native_meaning_not_host_inventory_order() {
    let original = render_document("relay-information", relay_input(relay_owners()))
        .expect("unique native references");
    assert!(
        original.contains("<td><code>HttpClient</code></td><td><code>client&lt;&amp;</code></td>")
    );
    assert!(original.contains("<td><code>get</code></td><td><code>client-get</code></td>"));
    assert!(!original.contains("not-the-client"));
    assert!(original.contains("<td><code>custom&lt;&amp;</code></td><td>123</td>"));
    assert!(
        original.find("custom&lt;&amp;").expect("first limit")
            < original.find("other</code>").expect("second limit")
    );
    let mut reversed = relay_owners();
    reversed.reverse();
    assert_eq!(
        render_document("relay-information", relay_input(reversed)).expect("permuted"),
        original
    );
    for index in 0..2 {
        let mut missing = relay_owners();
        missing.remove(index);
        assert!(render_document("relay-information", relay_input(missing)).is_err());
        let mut duplicate = relay_owners();
        duplicate.push(duplicate[index].clone());
        let error = render_document("relay-information", relay_input(duplicate))
            .expect_err("ambiguous reference");
        assert!(error.contains("matches=2"));
    }
    let mut wrong_parent = relay_owners();
    wrong_parent[1]["parent"] = json!("not-client");
    assert!(
        render_document("relay-information", relay_input(wrong_parent))
            .expect_err("wrong parent")
            .contains("operation/get: matches=0")
    );
}

fn stateful_owners() -> Vec<Value> {
    let mut owners = vec![
        owner("interface", "ByteStream", "", "stream"),
        owner("operation", "read-all", "stream", "read"),
        owner("interface", "DataStore", "", "data"),
    ];
    for name in [
        "schema-read",
        "transaction",
        "schema-set",
        "get",
        "scan",
        "put",
        "delete",
    ] {
        owners.push(owner("operation", name, "data", &format!("data-{name}")));
    }
    for name in ["json-decode-or", "json-encode", "list-length", "list-get"] {
        owners.push(owner("external", name, "", &format!("external-{name}")));
    }
    owners.push(owner("variant", "DataKeyPart", "", "key"));
    owners.push(owner("record", "DataEntry", "", "entry"));
    for name in ["data-encode", "data-decode-or"] {
        owners.push(owner("external", name, "", &format!("external-{name}")));
    }
    owners
}

#[test]
fn stateful_native_page_requires_each_unique_reference_and_preserves_authored_order() {
    let owners = stateful_owners();
    let actual =
        render_document("stateful-http", json!([build_input(), owners])).expect("stateful guide");
    let mut position = 0;
    for item in &owners {
        let cell = format!(
            "<td><code>{}</code></td>",
            item["reference"].as_str().expect("reference")
        );
        position += actual[position..]
            .find(&cell)
            .expect("next expected reference")
            + cell.len();
    }
    assert!(actual.contains("walkthrough.dependency operation=add.dependency"));
    for index in 0..owners.len() {
        let mut missing = owners.clone();
        missing.remove(index);
        assert!(render_document("stateful-http", json!([build_input(), missing])).is_err());
        let mut duplicate = owners.clone();
        duplicate.push(duplicate[index].clone());
        assert!(render_document("stateful-http", json!([build_input(), duplicate])).is_err());
    }
    let mut reversed = owners;
    reversed.reverse();
    assert_eq!(
        render_document("stateful-http", json!([build_input(), reversed])).expect("reversed"),
        actual
    );
}

#[test]
fn new_native_targets_admit_exact_typed_observations() {
    assert!(render("change-grammar", json!([build_input(), "not a list"])).is_err());
    assert!(render("deployment", json!([build_input(), 7])).is_err());
    assert!(
        render(
            "builtin-standard",
            json!([build_input(), {"package":"p","revision":"r"}])
        )
        .is_err()
    );
    let mut wrong = relay_input(relay_owners());
    wrong[3][0]["maximum"] = json!("123");
    assert!(render_document("relay-information", wrong).is_err());
    let mut unknown = relay_input(relay_owners());
    unknown[2][0]["extra"] = json!(true);
    assert!(render_document("relay-information", unknown).is_err());
}
